package com.adam.dao;

import com.adam.entity.OrderRoom;
import com.adam.entity.OrderRoomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    int deleteByExample(OrderRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    int insert(OrderRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    int insertSelective(OrderRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    List<OrderRoom> selectByExample(OrderRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    OrderRoom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderRoom record, @Param("example") OrderRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    int updateByExample(@Param("record") OrderRoom record, @Param("example") OrderRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    int updateByPrimaryKeySelective(OrderRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    int updateByPrimaryKey(OrderRoom record);
}