package com.adam.dao;

import com.adam.entity.OrderStatistics;
import com.adam.entity.OrderStatisticsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderStatistics
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int deleteByExample(OrderStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderStatistics
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderStatistics
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int insert(OrderStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderStatistics
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int insertSelective(OrderStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderStatistics
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    List<OrderStatistics> selectByExample(OrderStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderStatistics
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    OrderStatistics selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderStatistics
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderStatistics record, @Param("example") OrderStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderStatistics
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int updateByExample(@Param("record") OrderStatistics record, @Param("example") OrderStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderStatistics
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int updateByPrimaryKeySelective(OrderStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderStatistics
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int updateByPrimaryKey(OrderStatistics record);
}