package com.adam.dao;

import com.adam.entity.Orders;
import com.adam.entity.OrdersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int deleteByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    List<Orders> selectByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    Orders selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int updateByExample(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Orders
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    int updateByPrimaryKey(Orders record);
}