package com.example.newdemodemo.entity;

import java.io.Serializable;

public class OrderExtendInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.ID
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEOrderId
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private Long oeorderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEOrderNo
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private String oeorderno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEAttachment
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private String oeattachment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEMerchantId
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private Integer oemerchantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEWeChatUnionId
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private String oewechatunionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEMerchantName
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private String oemerchantname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEHotelPreference
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private String oehotelpreference;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEHotelPreferenceEN
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private String oehotelpreferenceen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEExpenseMoneyDesc
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private String oeexpensemoneydesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEWindowDesc
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private String oewindowdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEMRoomType
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private String oemroomtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEDetailSearchId
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private String oedetailsearchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEElongPName
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private String oeelongpname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OEOtherProductInfo
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private String oeotherproductinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderExtendInfo.OESupplierName
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private String oesuppliername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderExtendInfo
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.ID
     *
     * @return the value of OrderExtendInfo.ID
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.ID
     *
     * @param id the value for OrderExtendInfo.ID
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEOrderId
     *
     * @return the value of OrderExtendInfo.OEOrderId
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public Long getOeorderid() {
        return oeorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEOrderId
     *
     * @param oeorderid the value for OrderExtendInfo.OEOrderId
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOeorderid(Long oeorderid) {
        this.oeorderid = oeorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEOrderNo
     *
     * @return the value of OrderExtendInfo.OEOrderNo
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOeorderno() {
        return oeorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEOrderNo
     *
     * @param oeorderno the value for OrderExtendInfo.OEOrderNo
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOeorderno(String oeorderno) {
        this.oeorderno = oeorderno == null ? null : oeorderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEAttachment
     *
     * @return the value of OrderExtendInfo.OEAttachment
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOeattachment() {
        return oeattachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEAttachment
     *
     * @param oeattachment the value for OrderExtendInfo.OEAttachment
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOeattachment(String oeattachment) {
        this.oeattachment = oeattachment == null ? null : oeattachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEMerchantId
     *
     * @return the value of OrderExtendInfo.OEMerchantId
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public Integer getOemerchantid() {
        return oemerchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEMerchantId
     *
     * @param oemerchantid the value for OrderExtendInfo.OEMerchantId
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOemerchantid(Integer oemerchantid) {
        this.oemerchantid = oemerchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEWeChatUnionId
     *
     * @return the value of OrderExtendInfo.OEWeChatUnionId
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOewechatunionid() {
        return oewechatunionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEWeChatUnionId
     *
     * @param oewechatunionid the value for OrderExtendInfo.OEWeChatUnionId
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOewechatunionid(String oewechatunionid) {
        this.oewechatunionid = oewechatunionid == null ? null : oewechatunionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEMerchantName
     *
     * @return the value of OrderExtendInfo.OEMerchantName
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOemerchantname() {
        return oemerchantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEMerchantName
     *
     * @param oemerchantname the value for OrderExtendInfo.OEMerchantName
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOemerchantname(String oemerchantname) {
        this.oemerchantname = oemerchantname == null ? null : oemerchantname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEHotelPreference
     *
     * @return the value of OrderExtendInfo.OEHotelPreference
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOehotelpreference() {
        return oehotelpreference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEHotelPreference
     *
     * @param oehotelpreference the value for OrderExtendInfo.OEHotelPreference
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOehotelpreference(String oehotelpreference) {
        this.oehotelpreference = oehotelpreference == null ? null : oehotelpreference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEHotelPreferenceEN
     *
     * @return the value of OrderExtendInfo.OEHotelPreferenceEN
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOehotelpreferenceen() {
        return oehotelpreferenceen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEHotelPreferenceEN
     *
     * @param oehotelpreferenceen the value for OrderExtendInfo.OEHotelPreferenceEN
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOehotelpreferenceen(String oehotelpreferenceen) {
        this.oehotelpreferenceen = oehotelpreferenceen == null ? null : oehotelpreferenceen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEExpenseMoneyDesc
     *
     * @return the value of OrderExtendInfo.OEExpenseMoneyDesc
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOeexpensemoneydesc() {
        return oeexpensemoneydesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEExpenseMoneyDesc
     *
     * @param oeexpensemoneydesc the value for OrderExtendInfo.OEExpenseMoneyDesc
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOeexpensemoneydesc(String oeexpensemoneydesc) {
        this.oeexpensemoneydesc = oeexpensemoneydesc == null ? null : oeexpensemoneydesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEWindowDesc
     *
     * @return the value of OrderExtendInfo.OEWindowDesc
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOewindowdesc() {
        return oewindowdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEWindowDesc
     *
     * @param oewindowdesc the value for OrderExtendInfo.OEWindowDesc
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOewindowdesc(String oewindowdesc) {
        this.oewindowdesc = oewindowdesc == null ? null : oewindowdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEMRoomType
     *
     * @return the value of OrderExtendInfo.OEMRoomType
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOemroomtype() {
        return oemroomtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEMRoomType
     *
     * @param oemroomtype the value for OrderExtendInfo.OEMRoomType
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOemroomtype(String oemroomtype) {
        this.oemroomtype = oemroomtype == null ? null : oemroomtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEDetailSearchId
     *
     * @return the value of OrderExtendInfo.OEDetailSearchId
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOedetailsearchid() {
        return oedetailsearchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEDetailSearchId
     *
     * @param oedetailsearchid the value for OrderExtendInfo.OEDetailSearchId
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOedetailsearchid(String oedetailsearchid) {
        this.oedetailsearchid = oedetailsearchid == null ? null : oedetailsearchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEElongPName
     *
     * @return the value of OrderExtendInfo.OEElongPName
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOeelongpname() {
        return oeelongpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEElongPName
     *
     * @param oeelongpname the value for OrderExtendInfo.OEElongPName
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOeelongpname(String oeelongpname) {
        this.oeelongpname = oeelongpname == null ? null : oeelongpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OEOtherProductInfo
     *
     * @return the value of OrderExtendInfo.OEOtherProductInfo
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOeotherproductinfo() {
        return oeotherproductinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OEOtherProductInfo
     *
     * @param oeotherproductinfo the value for OrderExtendInfo.OEOtherProductInfo
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOeotherproductinfo(String oeotherproductinfo) {
        this.oeotherproductinfo = oeotherproductinfo == null ? null : oeotherproductinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderExtendInfo.OESupplierName
     *
     * @return the value of OrderExtendInfo.OESupplierName
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOesuppliername() {
        return oesuppliername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderExtendInfo.OESupplierName
     *
     * @param oesuppliername the value for OrderExtendInfo.OESupplierName
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOesuppliername(String oesuppliername) {
        this.oesuppliername = oesuppliername == null ? null : oesuppliername.trim();
    }
}