package com.example.newdemodemo.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderCancelPolicyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public OrderCancelPolicyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOcporderidIsNull() {
            addCriterion("OCPOrderId is null");
            return (Criteria) this;
        }

        public Criteria andOcporderidIsNotNull() {
            addCriterion("OCPOrderId is not null");
            return (Criteria) this;
        }

        public Criteria andOcporderidEqualTo(Integer value) {
            addCriterion("OCPOrderId =", value, "ocporderid");
            return (Criteria) this;
        }

        public Criteria andOcporderidNotEqualTo(Integer value) {
            addCriterion("OCPOrderId <>", value, "ocporderid");
            return (Criteria) this;
        }

        public Criteria andOcporderidGreaterThan(Integer value) {
            addCriterion("OCPOrderId >", value, "ocporderid");
            return (Criteria) this;
        }

        public Criteria andOcporderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("OCPOrderId >=", value, "ocporderid");
            return (Criteria) this;
        }

        public Criteria andOcporderidLessThan(Integer value) {
            addCriterion("OCPOrderId <", value, "ocporderid");
            return (Criteria) this;
        }

        public Criteria andOcporderidLessThanOrEqualTo(Integer value) {
            addCriterion("OCPOrderId <=", value, "ocporderid");
            return (Criteria) this;
        }

        public Criteria andOcporderidIn(List<Integer> values) {
            addCriterion("OCPOrderId in", values, "ocporderid");
            return (Criteria) this;
        }

        public Criteria andOcporderidNotIn(List<Integer> values) {
            addCriterion("OCPOrderId not in", values, "ocporderid");
            return (Criteria) this;
        }

        public Criteria andOcporderidBetween(Integer value1, Integer value2) {
            addCriterion("OCPOrderId between", value1, value2, "ocporderid");
            return (Criteria) this;
        }

        public Criteria andOcporderidNotBetween(Integer value1, Integer value2) {
            addCriterion("OCPOrderId not between", value1, value2, "ocporderid");
            return (Criteria) this;
        }

        public Criteria andOcpordernoIsNull() {
            addCriterion("OCPOrderNo is null");
            return (Criteria) this;
        }

        public Criteria andOcpordernoIsNotNull() {
            addCriterion("OCPOrderNo is not null");
            return (Criteria) this;
        }

        public Criteria andOcpordernoEqualTo(String value) {
            addCriterion("OCPOrderNo =", value, "ocporderno");
            return (Criteria) this;
        }

        public Criteria andOcpordernoNotEqualTo(String value) {
            addCriterion("OCPOrderNo <>", value, "ocporderno");
            return (Criteria) this;
        }

        public Criteria andOcpordernoGreaterThan(String value) {
            addCriterion("OCPOrderNo >", value, "ocporderno");
            return (Criteria) this;
        }

        public Criteria andOcpordernoGreaterThanOrEqualTo(String value) {
            addCriterion("OCPOrderNo >=", value, "ocporderno");
            return (Criteria) this;
        }

        public Criteria andOcpordernoLessThan(String value) {
            addCriterion("OCPOrderNo <", value, "ocporderno");
            return (Criteria) this;
        }

        public Criteria andOcpordernoLessThanOrEqualTo(String value) {
            addCriterion("OCPOrderNo <=", value, "ocporderno");
            return (Criteria) this;
        }

        public Criteria andOcpordernoLike(String value) {
            addCriterion("OCPOrderNo like", value, "ocporderno");
            return (Criteria) this;
        }

        public Criteria andOcpordernoNotLike(String value) {
            addCriterion("OCPOrderNo not like", value, "ocporderno");
            return (Criteria) this;
        }

        public Criteria andOcpordernoIn(List<String> values) {
            addCriterion("OCPOrderNo in", values, "ocporderno");
            return (Criteria) this;
        }

        public Criteria andOcpordernoNotIn(List<String> values) {
            addCriterion("OCPOrderNo not in", values, "ocporderno");
            return (Criteria) this;
        }

        public Criteria andOcpordernoBetween(String value1, String value2) {
            addCriterion("OCPOrderNo between", value1, value2, "ocporderno");
            return (Criteria) this;
        }

        public Criteria andOcpordernoNotBetween(String value1, String value2) {
            addCriterion("OCPOrderNo not between", value1, value2, "ocporderno");
            return (Criteria) this;
        }

        public Criteria andOcpcancelstarttimeIsNull() {
            addCriterion("OCPCancelStartTime is null");
            return (Criteria) this;
        }

        public Criteria andOcpcancelstarttimeIsNotNull() {
            addCriterion("OCPCancelStartTime is not null");
            return (Criteria) this;
        }

        public Criteria andOcpcancelstarttimeEqualTo(Date value) {
            addCriterion("OCPCancelStartTime =", value, "ocpcancelstarttime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelstarttimeNotEqualTo(Date value) {
            addCriterion("OCPCancelStartTime <>", value, "ocpcancelstarttime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelstarttimeGreaterThan(Date value) {
            addCriterion("OCPCancelStartTime >", value, "ocpcancelstarttime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelstarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("OCPCancelStartTime >=", value, "ocpcancelstarttime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelstarttimeLessThan(Date value) {
            addCriterion("OCPCancelStartTime <", value, "ocpcancelstarttime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelstarttimeLessThanOrEqualTo(Date value) {
            addCriterion("OCPCancelStartTime <=", value, "ocpcancelstarttime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelstarttimeIn(List<Date> values) {
            addCriterion("OCPCancelStartTime in", values, "ocpcancelstarttime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelstarttimeNotIn(List<Date> values) {
            addCriterion("OCPCancelStartTime not in", values, "ocpcancelstarttime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelstarttimeBetween(Date value1, Date value2) {
            addCriterion("OCPCancelStartTime between", value1, value2, "ocpcancelstarttime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelstarttimeNotBetween(Date value1, Date value2) {
            addCriterion("OCPCancelStartTime not between", value1, value2, "ocpcancelstarttime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelendtimeIsNull() {
            addCriterion("OCPCancelEndTime is null");
            return (Criteria) this;
        }

        public Criteria andOcpcancelendtimeIsNotNull() {
            addCriterion("OCPCancelEndTime is not null");
            return (Criteria) this;
        }

        public Criteria andOcpcancelendtimeEqualTo(Date value) {
            addCriterion("OCPCancelEndTime =", value, "ocpcancelendtime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelendtimeNotEqualTo(Date value) {
            addCriterion("OCPCancelEndTime <>", value, "ocpcancelendtime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelendtimeGreaterThan(Date value) {
            addCriterion("OCPCancelEndTime >", value, "ocpcancelendtime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelendtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("OCPCancelEndTime >=", value, "ocpcancelendtime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelendtimeLessThan(Date value) {
            addCriterion("OCPCancelEndTime <", value, "ocpcancelendtime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelendtimeLessThanOrEqualTo(Date value) {
            addCriterion("OCPCancelEndTime <=", value, "ocpcancelendtime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelendtimeIn(List<Date> values) {
            addCriterion("OCPCancelEndTime in", values, "ocpcancelendtime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelendtimeNotIn(List<Date> values) {
            addCriterion("OCPCancelEndTime not in", values, "ocpcancelendtime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelendtimeBetween(Date value1, Date value2) {
            addCriterion("OCPCancelEndTime between", value1, value2, "ocpcancelendtime");
            return (Criteria) this;
        }

        public Criteria andOcpcancelendtimeNotBetween(Date value1, Date value2) {
            addCriterion("OCPCancelEndTime not between", value1, value2, "ocpcancelendtime");
            return (Criteria) this;
        }

        public Criteria andOcppenaltyIsNull() {
            addCriterion("OCPPenalty is null");
            return (Criteria) this;
        }

        public Criteria andOcppenaltyIsNotNull() {
            addCriterion("OCPPenalty is not null");
            return (Criteria) this;
        }

        public Criteria andOcppenaltyEqualTo(BigDecimal value) {
            addCriterion("OCPPenalty =", value, "ocppenalty");
            return (Criteria) this;
        }

        public Criteria andOcppenaltyNotEqualTo(BigDecimal value) {
            addCriterion("OCPPenalty <>", value, "ocppenalty");
            return (Criteria) this;
        }

        public Criteria andOcppenaltyGreaterThan(BigDecimal value) {
            addCriterion("OCPPenalty >", value, "ocppenalty");
            return (Criteria) this;
        }

        public Criteria andOcppenaltyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OCPPenalty >=", value, "ocppenalty");
            return (Criteria) this;
        }

        public Criteria andOcppenaltyLessThan(BigDecimal value) {
            addCriterion("OCPPenalty <", value, "ocppenalty");
            return (Criteria) this;
        }

        public Criteria andOcppenaltyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OCPPenalty <=", value, "ocppenalty");
            return (Criteria) this;
        }

        public Criteria andOcppenaltyIn(List<BigDecimal> values) {
            addCriterion("OCPPenalty in", values, "ocppenalty");
            return (Criteria) this;
        }

        public Criteria andOcppenaltyNotIn(List<BigDecimal> values) {
            addCriterion("OCPPenalty not in", values, "ocppenalty");
            return (Criteria) this;
        }

        public Criteria andOcppenaltyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OCPPenalty between", value1, value2, "ocppenalty");
            return (Criteria) this;
        }

        public Criteria andOcppenaltyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OCPPenalty not between", value1, value2, "ocppenalty");
            return (Criteria) this;
        }

        public Criteria andOcpcurrencyidIsNull() {
            addCriterion("OCPCurrencyID is null");
            return (Criteria) this;
        }

        public Criteria andOcpcurrencyidIsNotNull() {
            addCriterion("OCPCurrencyID is not null");
            return (Criteria) this;
        }

        public Criteria andOcpcurrencyidEqualTo(Integer value) {
            addCriterion("OCPCurrencyID =", value, "ocpcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcurrencyidNotEqualTo(Integer value) {
            addCriterion("OCPCurrencyID <>", value, "ocpcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcurrencyidGreaterThan(Integer value) {
            addCriterion("OCPCurrencyID >", value, "ocpcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcurrencyidGreaterThanOrEqualTo(Integer value) {
            addCriterion("OCPCurrencyID >=", value, "ocpcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcurrencyidLessThan(Integer value) {
            addCriterion("OCPCurrencyID <", value, "ocpcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcurrencyidLessThanOrEqualTo(Integer value) {
            addCriterion("OCPCurrencyID <=", value, "ocpcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcurrencyidIn(List<Integer> values) {
            addCriterion("OCPCurrencyID in", values, "ocpcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcurrencyidNotIn(List<Integer> values) {
            addCriterion("OCPCurrencyID not in", values, "ocpcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcurrencyidBetween(Integer value1, Integer value2) {
            addCriterion("OCPCurrencyID between", value1, value2, "ocpcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcurrencyidNotBetween(Integer value1, Integer value2) {
            addCriterion("OCPCurrencyID not between", value1, value2, "ocpcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyIsNull() {
            addCriterion("OCPSupplierCancelPolicy is null");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyIsNotNull() {
            addCriterion("OCPSupplierCancelPolicy is not null");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyEqualTo(String value) {
            addCriterion("OCPSupplierCancelPolicy =", value, "ocpsuppliercancelpolicy");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyNotEqualTo(String value) {
            addCriterion("OCPSupplierCancelPolicy <>", value, "ocpsuppliercancelpolicy");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyGreaterThan(String value) {
            addCriterion("OCPSupplierCancelPolicy >", value, "ocpsuppliercancelpolicy");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyGreaterThanOrEqualTo(String value) {
            addCriterion("OCPSupplierCancelPolicy >=", value, "ocpsuppliercancelpolicy");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyLessThan(String value) {
            addCriterion("OCPSupplierCancelPolicy <", value, "ocpsuppliercancelpolicy");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyLessThanOrEqualTo(String value) {
            addCriterion("OCPSupplierCancelPolicy <=", value, "ocpsuppliercancelpolicy");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyLike(String value) {
            addCriterion("OCPSupplierCancelPolicy like", value, "ocpsuppliercancelpolicy");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyNotLike(String value) {
            addCriterion("OCPSupplierCancelPolicy not like", value, "ocpsuppliercancelpolicy");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyIn(List<String> values) {
            addCriterion("OCPSupplierCancelPolicy in", values, "ocpsuppliercancelpolicy");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyNotIn(List<String> values) {
            addCriterion("OCPSupplierCancelPolicy not in", values, "ocpsuppliercancelpolicy");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyBetween(String value1, String value2) {
            addCriterion("OCPSupplierCancelPolicy between", value1, value2, "ocpsuppliercancelpolicy");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercancelpolicyNotBetween(String value1, String value2) {
            addCriterion("OCPSupplierCancelPolicy not between", value1, value2, "ocpsuppliercancelpolicy");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionIsNull() {
            addCriterion("OCPSupplierDescription is null");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionIsNotNull() {
            addCriterion("OCPSupplierDescription is not null");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionEqualTo(String value) {
            addCriterion("OCPSupplierDescription =", value, "ocpsupplierdescription");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionNotEqualTo(String value) {
            addCriterion("OCPSupplierDescription <>", value, "ocpsupplierdescription");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionGreaterThan(String value) {
            addCriterion("OCPSupplierDescription >", value, "ocpsupplierdescription");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("OCPSupplierDescription >=", value, "ocpsupplierdescription");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionLessThan(String value) {
            addCriterion("OCPSupplierDescription <", value, "ocpsupplierdescription");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionLessThanOrEqualTo(String value) {
            addCriterion("OCPSupplierDescription <=", value, "ocpsupplierdescription");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionLike(String value) {
            addCriterion("OCPSupplierDescription like", value, "ocpsupplierdescription");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionNotLike(String value) {
            addCriterion("OCPSupplierDescription not like", value, "ocpsupplierdescription");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionIn(List<String> values) {
            addCriterion("OCPSupplierDescription in", values, "ocpsupplierdescription");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionNotIn(List<String> values) {
            addCriterion("OCPSupplierDescription not in", values, "ocpsupplierdescription");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionBetween(String value1, String value2) {
            addCriterion("OCPSupplierDescription between", value1, value2, "ocpsupplierdescription");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierdescriptionNotBetween(String value1, String value2) {
            addCriterion("OCPSupplierDescription not between", value1, value2, "ocpsupplierdescription");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierpenaltyIsNull() {
            addCriterion("OCPSupplierPenalty is null");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierpenaltyIsNotNull() {
            addCriterion("OCPSupplierPenalty is not null");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierpenaltyEqualTo(BigDecimal value) {
            addCriterion("OCPSupplierPenalty =", value, "ocpsupplierpenalty");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierpenaltyNotEqualTo(BigDecimal value) {
            addCriterion("OCPSupplierPenalty <>", value, "ocpsupplierpenalty");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierpenaltyGreaterThan(BigDecimal value) {
            addCriterion("OCPSupplierPenalty >", value, "ocpsupplierpenalty");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierpenaltyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OCPSupplierPenalty >=", value, "ocpsupplierpenalty");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierpenaltyLessThan(BigDecimal value) {
            addCriterion("OCPSupplierPenalty <", value, "ocpsupplierpenalty");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierpenaltyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OCPSupplierPenalty <=", value, "ocpsupplierpenalty");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierpenaltyIn(List<BigDecimal> values) {
            addCriterion("OCPSupplierPenalty in", values, "ocpsupplierpenalty");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierpenaltyNotIn(List<BigDecimal> values) {
            addCriterion("OCPSupplierPenalty not in", values, "ocpsupplierpenalty");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierpenaltyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OCPSupplierPenalty between", value1, value2, "ocpsupplierpenalty");
            return (Criteria) this;
        }

        public Criteria andOcpsupplierpenaltyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OCPSupplierPenalty not between", value1, value2, "ocpsupplierpenalty");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyidIsNull() {
            addCriterion("OCPCustomerCurrencyId is null");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyidIsNotNull() {
            addCriterion("OCPCustomerCurrencyId is not null");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyidEqualTo(Integer value) {
            addCriterion("OCPCustomerCurrencyId =", value, "ocpcustomercurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyidNotEqualTo(Integer value) {
            addCriterion("OCPCustomerCurrencyId <>", value, "ocpcustomercurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyidGreaterThan(Integer value) {
            addCriterion("OCPCustomerCurrencyId >", value, "ocpcustomercurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyidGreaterThanOrEqualTo(Integer value) {
            addCriterion("OCPCustomerCurrencyId >=", value, "ocpcustomercurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyidLessThan(Integer value) {
            addCriterion("OCPCustomerCurrencyId <", value, "ocpcustomercurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyidLessThanOrEqualTo(Integer value) {
            addCriterion("OCPCustomerCurrencyId <=", value, "ocpcustomercurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyidIn(List<Integer> values) {
            addCriterion("OCPCustomerCurrencyId in", values, "ocpcustomercurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyidNotIn(List<Integer> values) {
            addCriterion("OCPCustomerCurrencyId not in", values, "ocpcustomercurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyidBetween(Integer value1, Integer value2) {
            addCriterion("OCPCustomerCurrencyId between", value1, value2, "ocpcustomercurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyidNotBetween(Integer value1, Integer value2) {
            addCriterion("OCPCustomerCurrencyId not between", value1, value2, "ocpcustomercurrencyid");
            return (Criteria) this;
        }

        public Criteria andOcpisrefundableIsNull() {
            addCriterion("OCPIsRefundable is null");
            return (Criteria) this;
        }

        public Criteria andOcpisrefundableIsNotNull() {
            addCriterion("OCPIsRefundable is not null");
            return (Criteria) this;
        }

        public Criteria andOcpisrefundableEqualTo(Boolean value) {
            addCriterion("OCPIsRefundable =", value, "ocpisrefundable");
            return (Criteria) this;
        }

        public Criteria andOcpisrefundableNotEqualTo(Boolean value) {
            addCriterion("OCPIsRefundable <>", value, "ocpisrefundable");
            return (Criteria) this;
        }

        public Criteria andOcpisrefundableGreaterThan(Boolean value) {
            addCriterion("OCPIsRefundable >", value, "ocpisrefundable");
            return (Criteria) this;
        }

        public Criteria andOcpisrefundableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("OCPIsRefundable >=", value, "ocpisrefundable");
            return (Criteria) this;
        }

        public Criteria andOcpisrefundableLessThan(Boolean value) {
            addCriterion("OCPIsRefundable <", value, "ocpisrefundable");
            return (Criteria) this;
        }

        public Criteria andOcpisrefundableLessThanOrEqualTo(Boolean value) {
            addCriterion("OCPIsRefundable <=", value, "ocpisrefundable");
            return (Criteria) this;
        }

        public Criteria andOcpisrefundableIn(List<Boolean> values) {
            addCriterion("OCPIsRefundable in", values, "ocpisrefundable");
            return (Criteria) this;
        }

        public Criteria andOcpisrefundableNotIn(List<Boolean> values) {
            addCriterion("OCPIsRefundable not in", values, "ocpisrefundable");
            return (Criteria) this;
        }

        public Criteria andOcpisrefundableBetween(Boolean value1, Boolean value2) {
            addCriterion("OCPIsRefundable between", value1, value2, "ocpisrefundable");
            return (Criteria) this;
        }

        public Criteria andOcpisrefundableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("OCPIsRefundable not between", value1, value2, "ocpisrefundable");
            return (Criteria) this;
        }

        public Criteria andOcplocalstartdateIsNull() {
            addCriterion("OCPLocalStartDate is null");
            return (Criteria) this;
        }

        public Criteria andOcplocalstartdateIsNotNull() {
            addCriterion("OCPLocalStartDate is not null");
            return (Criteria) this;
        }

        public Criteria andOcplocalstartdateEqualTo(Date value) {
            addCriterion("OCPLocalStartDate =", value, "ocplocalstartdate");
            return (Criteria) this;
        }

        public Criteria andOcplocalstartdateNotEqualTo(Date value) {
            addCriterion("OCPLocalStartDate <>", value, "ocplocalstartdate");
            return (Criteria) this;
        }

        public Criteria andOcplocalstartdateGreaterThan(Date value) {
            addCriterion("OCPLocalStartDate >", value, "ocplocalstartdate");
            return (Criteria) this;
        }

        public Criteria andOcplocalstartdateGreaterThanOrEqualTo(Date value) {
            addCriterion("OCPLocalStartDate >=", value, "ocplocalstartdate");
            return (Criteria) this;
        }

        public Criteria andOcplocalstartdateLessThan(Date value) {
            addCriterion("OCPLocalStartDate <", value, "ocplocalstartdate");
            return (Criteria) this;
        }

        public Criteria andOcplocalstartdateLessThanOrEqualTo(Date value) {
            addCriterion("OCPLocalStartDate <=", value, "ocplocalstartdate");
            return (Criteria) this;
        }

        public Criteria andOcplocalstartdateIn(List<Date> values) {
            addCriterion("OCPLocalStartDate in", values, "ocplocalstartdate");
            return (Criteria) this;
        }

        public Criteria andOcplocalstartdateNotIn(List<Date> values) {
            addCriterion("OCPLocalStartDate not in", values, "ocplocalstartdate");
            return (Criteria) this;
        }

        public Criteria andOcplocalstartdateBetween(Date value1, Date value2) {
            addCriterion("OCPLocalStartDate between", value1, value2, "ocplocalstartdate");
            return (Criteria) this;
        }

        public Criteria andOcplocalstartdateNotBetween(Date value1, Date value2) {
            addCriterion("OCPLocalStartDate not between", value1, value2, "ocplocalstartdate");
            return (Criteria) this;
        }

        public Criteria andOcplocalenddateIsNull() {
            addCriterion("OCPLocalEndDate is null");
            return (Criteria) this;
        }

        public Criteria andOcplocalenddateIsNotNull() {
            addCriterion("OCPLocalEndDate is not null");
            return (Criteria) this;
        }

        public Criteria andOcplocalenddateEqualTo(Date value) {
            addCriterion("OCPLocalEndDate =", value, "ocplocalenddate");
            return (Criteria) this;
        }

        public Criteria andOcplocalenddateNotEqualTo(Date value) {
            addCriterion("OCPLocalEndDate <>", value, "ocplocalenddate");
            return (Criteria) this;
        }

        public Criteria andOcplocalenddateGreaterThan(Date value) {
            addCriterion("OCPLocalEndDate >", value, "ocplocalenddate");
            return (Criteria) this;
        }

        public Criteria andOcplocalenddateGreaterThanOrEqualTo(Date value) {
            addCriterion("OCPLocalEndDate >=", value, "ocplocalenddate");
            return (Criteria) this;
        }

        public Criteria andOcplocalenddateLessThan(Date value) {
            addCriterion("OCPLocalEndDate <", value, "ocplocalenddate");
            return (Criteria) this;
        }

        public Criteria andOcplocalenddateLessThanOrEqualTo(Date value) {
            addCriterion("OCPLocalEndDate <=", value, "ocplocalenddate");
            return (Criteria) this;
        }

        public Criteria andOcplocalenddateIn(List<Date> values) {
            addCriterion("OCPLocalEndDate in", values, "ocplocalenddate");
            return (Criteria) this;
        }

        public Criteria andOcplocalenddateNotIn(List<Date> values) {
            addCriterion("OCPLocalEndDate not in", values, "ocplocalenddate");
            return (Criteria) this;
        }

        public Criteria andOcplocalenddateBetween(Date value1, Date value2) {
            addCriterion("OCPLocalEndDate between", value1, value2, "ocplocalenddate");
            return (Criteria) this;
        }

        public Criteria andOcplocalenddateNotBetween(Date value1, Date value2) {
            addCriterion("OCPLocalEndDate not between", value1, value2, "ocplocalenddate");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercurrencyrateIsNull() {
            addCriterion("OCPSupplierCurrencyRate is null");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercurrencyrateIsNotNull() {
            addCriterion("OCPSupplierCurrencyRate is not null");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercurrencyrateEqualTo(BigDecimal value) {
            addCriterion("OCPSupplierCurrencyRate =", value, "ocpsuppliercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercurrencyrateNotEqualTo(BigDecimal value) {
            addCriterion("OCPSupplierCurrencyRate <>", value, "ocpsuppliercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercurrencyrateGreaterThan(BigDecimal value) {
            addCriterion("OCPSupplierCurrencyRate >", value, "ocpsuppliercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercurrencyrateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OCPSupplierCurrencyRate >=", value, "ocpsuppliercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercurrencyrateLessThan(BigDecimal value) {
            addCriterion("OCPSupplierCurrencyRate <", value, "ocpsuppliercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercurrencyrateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OCPSupplierCurrencyRate <=", value, "ocpsuppliercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercurrencyrateIn(List<BigDecimal> values) {
            addCriterion("OCPSupplierCurrencyRate in", values, "ocpsuppliercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercurrencyrateNotIn(List<BigDecimal> values) {
            addCriterion("OCPSupplierCurrencyRate not in", values, "ocpsuppliercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercurrencyrateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OCPSupplierCurrencyRate between", value1, value2, "ocpsuppliercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpsuppliercurrencyrateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OCPSupplierCurrencyRate not between", value1, value2, "ocpsuppliercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyrateIsNull() {
            addCriterion("OCPCustomerCurrencyRate is null");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyrateIsNotNull() {
            addCriterion("OCPCustomerCurrencyRate is not null");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyrateEqualTo(BigDecimal value) {
            addCriterion("OCPCustomerCurrencyRate =", value, "ocpcustomercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyrateNotEqualTo(BigDecimal value) {
            addCriterion("OCPCustomerCurrencyRate <>", value, "ocpcustomercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyrateGreaterThan(BigDecimal value) {
            addCriterion("OCPCustomerCurrencyRate >", value, "ocpcustomercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyrateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OCPCustomerCurrencyRate >=", value, "ocpcustomercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyrateLessThan(BigDecimal value) {
            addCriterion("OCPCustomerCurrencyRate <", value, "ocpcustomercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyrateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OCPCustomerCurrencyRate <=", value, "ocpcustomercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyrateIn(List<BigDecimal> values) {
            addCriterion("OCPCustomerCurrencyRate in", values, "ocpcustomercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyrateNotIn(List<BigDecimal> values) {
            addCriterion("OCPCustomerCurrencyRate not in", values, "ocpcustomercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyrateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OCPCustomerCurrencyRate between", value1, value2, "ocpcustomercurrencyrate");
            return (Criteria) this;
        }

        public Criteria andOcpcustomercurrencyrateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OCPCustomerCurrencyRate not between", value1, value2, "ocpcustomercurrencyrate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 18 13:57:58 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderCancelPolicy
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}