package com.adam.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OrderAmountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    public OrderAmountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOaorderidIsNull() {
            addCriterion("OAOrderId is null");
            return (Criteria) this;
        }

        public Criteria andOaorderidIsNotNull() {
            addCriterion("OAOrderId is not null");
            return (Criteria) this;
        }

        public Criteria andOaorderidEqualTo(Integer value) {
            addCriterion("OAOrderId =", value, "oaorderid");
            return (Criteria) this;
        }

        public Criteria andOaorderidNotEqualTo(Integer value) {
            addCriterion("OAOrderId <>", value, "oaorderid");
            return (Criteria) this;
        }

        public Criteria andOaorderidGreaterThan(Integer value) {
            addCriterion("OAOrderId >", value, "oaorderid");
            return (Criteria) this;
        }

        public Criteria andOaorderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("OAOrderId >=", value, "oaorderid");
            return (Criteria) this;
        }

        public Criteria andOaorderidLessThan(Integer value) {
            addCriterion("OAOrderId <", value, "oaorderid");
            return (Criteria) this;
        }

        public Criteria andOaorderidLessThanOrEqualTo(Integer value) {
            addCriterion("OAOrderId <=", value, "oaorderid");
            return (Criteria) this;
        }

        public Criteria andOaorderidIn(List<Integer> values) {
            addCriterion("OAOrderId in", values, "oaorderid");
            return (Criteria) this;
        }

        public Criteria andOaorderidNotIn(List<Integer> values) {
            addCriterion("OAOrderId not in", values, "oaorderid");
            return (Criteria) this;
        }

        public Criteria andOaorderidBetween(Integer value1, Integer value2) {
            addCriterion("OAOrderId between", value1, value2, "oaorderid");
            return (Criteria) this;
        }

        public Criteria andOaorderidNotBetween(Integer value1, Integer value2) {
            addCriterion("OAOrderId not between", value1, value2, "oaorderid");
            return (Criteria) this;
        }

        public Criteria andOaordernoIsNull() {
            addCriterion("OAOrderNo is null");
            return (Criteria) this;
        }

        public Criteria andOaordernoIsNotNull() {
            addCriterion("OAOrderNo is not null");
            return (Criteria) this;
        }

        public Criteria andOaordernoEqualTo(String value) {
            addCriterion("OAOrderNo =", value, "oaorderno");
            return (Criteria) this;
        }

        public Criteria andOaordernoNotEqualTo(String value) {
            addCriterion("OAOrderNo <>", value, "oaorderno");
            return (Criteria) this;
        }

        public Criteria andOaordernoGreaterThan(String value) {
            addCriterion("OAOrderNo >", value, "oaorderno");
            return (Criteria) this;
        }

        public Criteria andOaordernoGreaterThanOrEqualTo(String value) {
            addCriterion("OAOrderNo >=", value, "oaorderno");
            return (Criteria) this;
        }

        public Criteria andOaordernoLessThan(String value) {
            addCriterion("OAOrderNo <", value, "oaorderno");
            return (Criteria) this;
        }

        public Criteria andOaordernoLessThanOrEqualTo(String value) {
            addCriterion("OAOrderNo <=", value, "oaorderno");
            return (Criteria) this;
        }

        public Criteria andOaordernoLike(String value) {
            addCriterion("OAOrderNo like", value, "oaorderno");
            return (Criteria) this;
        }

        public Criteria andOaordernoNotLike(String value) {
            addCriterion("OAOrderNo not like", value, "oaorderno");
            return (Criteria) this;
        }

        public Criteria andOaordernoIn(List<String> values) {
            addCriterion("OAOrderNo in", values, "oaorderno");
            return (Criteria) this;
        }

        public Criteria andOaordernoNotIn(List<String> values) {
            addCriterion("OAOrderNo not in", values, "oaorderno");
            return (Criteria) this;
        }

        public Criteria andOaordernoBetween(String value1, String value2) {
            addCriterion("OAOrderNo between", value1, value2, "oaorderno");
            return (Criteria) this;
        }

        public Criteria andOaordernoNotBetween(String value1, String value2) {
            addCriterion("OAOrderNo not between", value1, value2, "oaorderno");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoriIsNull() {
            addCriterion("OAOrderCostPriceOri is null");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoriIsNotNull() {
            addCriterion("OAOrderCostPriceOri is not null");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoriEqualTo(BigDecimal value) {
            addCriterion("OAOrderCostPriceOri =", value, "oaordercostpriceori");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoriNotEqualTo(BigDecimal value) {
            addCriterion("OAOrderCostPriceOri <>", value, "oaordercostpriceori");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoriGreaterThan(BigDecimal value) {
            addCriterion("OAOrderCostPriceOri >", value, "oaordercostpriceori");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoriGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderCostPriceOri >=", value, "oaordercostpriceori");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoriLessThan(BigDecimal value) {
            addCriterion("OAOrderCostPriceOri <", value, "oaordercostpriceori");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoriLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderCostPriceOri <=", value, "oaordercostpriceori");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoriIn(List<BigDecimal> values) {
            addCriterion("OAOrderCostPriceOri in", values, "oaordercostpriceori");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoriNotIn(List<BigDecimal> values) {
            addCriterion("OAOrderCostPriceOri not in", values, "oaordercostpriceori");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoriBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderCostPriceOri between", value1, value2, "oaordercostpriceori");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoriNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderCostPriceOri not between", value1, value2, "oaordercostpriceori");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoricurrencyIsNull() {
            addCriterion("OAOrderCostPriceOriCurrency is null");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoricurrencyIsNotNull() {
            addCriterion("OAOrderCostPriceOriCurrency is not null");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoricurrencyEqualTo(Integer value) {
            addCriterion("OAOrderCostPriceOriCurrency =", value, "oaordercostpriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoricurrencyNotEqualTo(Integer value) {
            addCriterion("OAOrderCostPriceOriCurrency <>", value, "oaordercostpriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoricurrencyGreaterThan(Integer value) {
            addCriterion("OAOrderCostPriceOriCurrency >", value, "oaordercostpriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoricurrencyGreaterThanOrEqualTo(Integer value) {
            addCriterion("OAOrderCostPriceOriCurrency >=", value, "oaordercostpriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoricurrencyLessThan(Integer value) {
            addCriterion("OAOrderCostPriceOriCurrency <", value, "oaordercostpriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoricurrencyLessThanOrEqualTo(Integer value) {
            addCriterion("OAOrderCostPriceOriCurrency <=", value, "oaordercostpriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoricurrencyIn(List<Integer> values) {
            addCriterion("OAOrderCostPriceOriCurrency in", values, "oaordercostpriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoricurrencyNotIn(List<Integer> values) {
            addCriterion("OAOrderCostPriceOriCurrency not in", values, "oaordercostpriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoricurrencyBetween(Integer value1, Integer value2) {
            addCriterion("OAOrderCostPriceOriCurrency between", value1, value2, "oaordercostpriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaordercostpriceoricurrencyNotBetween(Integer value1, Integer value2) {
            addCriterion("OAOrderCostPriceOriCurrency not between", value1, value2, "oaordercostpriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaordercostpricecnyIsNull() {
            addCriterion("OAOrderCostPriceCNY is null");
            return (Criteria) this;
        }

        public Criteria andOaordercostpricecnyIsNotNull() {
            addCriterion("OAOrderCostPriceCNY is not null");
            return (Criteria) this;
        }

        public Criteria andOaordercostpricecnyEqualTo(BigDecimal value) {
            addCriterion("OAOrderCostPriceCNY =", value, "oaordercostpricecny");
            return (Criteria) this;
        }

        public Criteria andOaordercostpricecnyNotEqualTo(BigDecimal value) {
            addCriterion("OAOrderCostPriceCNY <>", value, "oaordercostpricecny");
            return (Criteria) this;
        }

        public Criteria andOaordercostpricecnyGreaterThan(BigDecimal value) {
            addCriterion("OAOrderCostPriceCNY >", value, "oaordercostpricecny");
            return (Criteria) this;
        }

        public Criteria andOaordercostpricecnyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderCostPriceCNY >=", value, "oaordercostpricecny");
            return (Criteria) this;
        }

        public Criteria andOaordercostpricecnyLessThan(BigDecimal value) {
            addCriterion("OAOrderCostPriceCNY <", value, "oaordercostpricecny");
            return (Criteria) this;
        }

        public Criteria andOaordercostpricecnyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderCostPriceCNY <=", value, "oaordercostpricecny");
            return (Criteria) this;
        }

        public Criteria andOaordercostpricecnyIn(List<BigDecimal> values) {
            addCriterion("OAOrderCostPriceCNY in", values, "oaordercostpricecny");
            return (Criteria) this;
        }

        public Criteria andOaordercostpricecnyNotIn(List<BigDecimal> values) {
            addCriterion("OAOrderCostPriceCNY not in", values, "oaordercostpricecny");
            return (Criteria) this;
        }

        public Criteria andOaordercostpricecnyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderCostPriceCNY between", value1, value2, "oaordercostpricecny");
            return (Criteria) this;
        }

        public Criteria andOaordercostpricecnyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderCostPriceCNY not between", value1, value2, "oaordercostpricecny");
            return (Criteria) this;
        }

        public Criteria andOaordercostexchangerateIsNull() {
            addCriterion("OAOrderCostExchangeRate is null");
            return (Criteria) this;
        }

        public Criteria andOaordercostexchangerateIsNotNull() {
            addCriterion("OAOrderCostExchangeRate is not null");
            return (Criteria) this;
        }

        public Criteria andOaordercostexchangerateEqualTo(BigDecimal value) {
            addCriterion("OAOrderCostExchangeRate =", value, "oaordercostexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordercostexchangerateNotEqualTo(BigDecimal value) {
            addCriterion("OAOrderCostExchangeRate <>", value, "oaordercostexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordercostexchangerateGreaterThan(BigDecimal value) {
            addCriterion("OAOrderCostExchangeRate >", value, "oaordercostexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordercostexchangerateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderCostExchangeRate >=", value, "oaordercostexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordercostexchangerateLessThan(BigDecimal value) {
            addCriterion("OAOrderCostExchangeRate <", value, "oaordercostexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordercostexchangerateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderCostExchangeRate <=", value, "oaordercostexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordercostexchangerateIn(List<BigDecimal> values) {
            addCriterion("OAOrderCostExchangeRate in", values, "oaordercostexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordercostexchangerateNotIn(List<BigDecimal> values) {
            addCriterion("OAOrderCostExchangeRate not in", values, "oaordercostexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordercostexchangerateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderCostExchangeRate between", value1, value2, "oaordercostexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordercostexchangerateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderCostExchangeRate not between", value1, value2, "oaordercostexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoriIsNull() {
            addCriterion("OAOrderOTAPriceOri is null");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoriIsNotNull() {
            addCriterion("OAOrderOTAPriceOri is not null");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoriEqualTo(BigDecimal value) {
            addCriterion("OAOrderOTAPriceOri =", value, "oaorderotapriceori");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoriNotEqualTo(BigDecimal value) {
            addCriterion("OAOrderOTAPriceOri <>", value, "oaorderotapriceori");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoriGreaterThan(BigDecimal value) {
            addCriterion("OAOrderOTAPriceOri >", value, "oaorderotapriceori");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoriGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderOTAPriceOri >=", value, "oaorderotapriceori");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoriLessThan(BigDecimal value) {
            addCriterion("OAOrderOTAPriceOri <", value, "oaorderotapriceori");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoriLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderOTAPriceOri <=", value, "oaorderotapriceori");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoriIn(List<BigDecimal> values) {
            addCriterion("OAOrderOTAPriceOri in", values, "oaorderotapriceori");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoriNotIn(List<BigDecimal> values) {
            addCriterion("OAOrderOTAPriceOri not in", values, "oaorderotapriceori");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoriBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderOTAPriceOri between", value1, value2, "oaorderotapriceori");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoriNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderOTAPriceOri not between", value1, value2, "oaorderotapriceori");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoricurrencyIsNull() {
            addCriterion("OAOrderOTAPriceOriCurrency is null");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoricurrencyIsNotNull() {
            addCriterion("OAOrderOTAPriceOriCurrency is not null");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoricurrencyEqualTo(Integer value) {
            addCriterion("OAOrderOTAPriceOriCurrency =", value, "oaorderotapriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoricurrencyNotEqualTo(Integer value) {
            addCriterion("OAOrderOTAPriceOriCurrency <>", value, "oaorderotapriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoricurrencyGreaterThan(Integer value) {
            addCriterion("OAOrderOTAPriceOriCurrency >", value, "oaorderotapriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoricurrencyGreaterThanOrEqualTo(Integer value) {
            addCriterion("OAOrderOTAPriceOriCurrency >=", value, "oaorderotapriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoricurrencyLessThan(Integer value) {
            addCriterion("OAOrderOTAPriceOriCurrency <", value, "oaorderotapriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoricurrencyLessThanOrEqualTo(Integer value) {
            addCriterion("OAOrderOTAPriceOriCurrency <=", value, "oaorderotapriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoricurrencyIn(List<Integer> values) {
            addCriterion("OAOrderOTAPriceOriCurrency in", values, "oaorderotapriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoricurrencyNotIn(List<Integer> values) {
            addCriterion("OAOrderOTAPriceOriCurrency not in", values, "oaorderotapriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoricurrencyBetween(Integer value1, Integer value2) {
            addCriterion("OAOrderOTAPriceOriCurrency between", value1, value2, "oaorderotapriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderotapriceoricurrencyNotBetween(Integer value1, Integer value2) {
            addCriterion("OAOrderOTAPriceOriCurrency not between", value1, value2, "oaorderotapriceoricurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderotapricecnyIsNull() {
            addCriterion("OAOrderOTAPriceCNY is null");
            return (Criteria) this;
        }

        public Criteria andOaorderotapricecnyIsNotNull() {
            addCriterion("OAOrderOTAPriceCNY is not null");
            return (Criteria) this;
        }

        public Criteria andOaorderotapricecnyEqualTo(BigDecimal value) {
            addCriterion("OAOrderOTAPriceCNY =", value, "oaorderotapricecny");
            return (Criteria) this;
        }

        public Criteria andOaorderotapricecnyNotEqualTo(BigDecimal value) {
            addCriterion("OAOrderOTAPriceCNY <>", value, "oaorderotapricecny");
            return (Criteria) this;
        }

        public Criteria andOaorderotapricecnyGreaterThan(BigDecimal value) {
            addCriterion("OAOrderOTAPriceCNY >", value, "oaorderotapricecny");
            return (Criteria) this;
        }

        public Criteria andOaorderotapricecnyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderOTAPriceCNY >=", value, "oaorderotapricecny");
            return (Criteria) this;
        }

        public Criteria andOaorderotapricecnyLessThan(BigDecimal value) {
            addCriterion("OAOrderOTAPriceCNY <", value, "oaorderotapricecny");
            return (Criteria) this;
        }

        public Criteria andOaorderotapricecnyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderOTAPriceCNY <=", value, "oaorderotapricecny");
            return (Criteria) this;
        }

        public Criteria andOaorderotapricecnyIn(List<BigDecimal> values) {
            addCriterion("OAOrderOTAPriceCNY in", values, "oaorderotapricecny");
            return (Criteria) this;
        }

        public Criteria andOaorderotapricecnyNotIn(List<BigDecimal> values) {
            addCriterion("OAOrderOTAPriceCNY not in", values, "oaorderotapricecny");
            return (Criteria) this;
        }

        public Criteria andOaorderotapricecnyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderOTAPriceCNY between", value1, value2, "oaorderotapricecny");
            return (Criteria) this;
        }

        public Criteria andOaorderotapricecnyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderOTAPriceCNY not between", value1, value2, "oaorderotapricecny");
            return (Criteria) this;
        }

        public Criteria andOaorderotaexchangerateIsNull() {
            addCriterion("OAOrderOTAExchangeRate is null");
            return (Criteria) this;
        }

        public Criteria andOaorderotaexchangerateIsNotNull() {
            addCriterion("OAOrderOTAExchangeRate is not null");
            return (Criteria) this;
        }

        public Criteria andOaorderotaexchangerateEqualTo(BigDecimal value) {
            addCriterion("OAOrderOTAExchangeRate =", value, "oaorderotaexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderotaexchangerateNotEqualTo(BigDecimal value) {
            addCriterion("OAOrderOTAExchangeRate <>", value, "oaorderotaexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderotaexchangerateGreaterThan(BigDecimal value) {
            addCriterion("OAOrderOTAExchangeRate >", value, "oaorderotaexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderotaexchangerateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderOTAExchangeRate >=", value, "oaorderotaexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderotaexchangerateLessThan(BigDecimal value) {
            addCriterion("OAOrderOTAExchangeRate <", value, "oaorderotaexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderotaexchangerateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderOTAExchangeRate <=", value, "oaorderotaexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderotaexchangerateIn(List<BigDecimal> values) {
            addCriterion("OAOrderOTAExchangeRate in", values, "oaorderotaexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderotaexchangerateNotIn(List<BigDecimal> values) {
            addCriterion("OAOrderOTAExchangeRate not in", values, "oaorderotaexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderotaexchangerateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderOTAExchangeRate between", value1, value2, "oaorderotaexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderotaexchangerateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderOTAExchangeRate not between", value1, value2, "oaorderotaexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementpriceIsNull() {
            addCriterion("OAOrderSettlementPrice is null");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementpriceIsNotNull() {
            addCriterion("OAOrderSettlementPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementpriceEqualTo(BigDecimal value) {
            addCriterion("OAOrderSettlementPrice =", value, "oaordersettlementprice");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementpriceNotEqualTo(BigDecimal value) {
            addCriterion("OAOrderSettlementPrice <>", value, "oaordersettlementprice");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementpriceGreaterThan(BigDecimal value) {
            addCriterion("OAOrderSettlementPrice >", value, "oaordersettlementprice");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderSettlementPrice >=", value, "oaordersettlementprice");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementpriceLessThan(BigDecimal value) {
            addCriterion("OAOrderSettlementPrice <", value, "oaordersettlementprice");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderSettlementPrice <=", value, "oaordersettlementprice");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementpriceIn(List<BigDecimal> values) {
            addCriterion("OAOrderSettlementPrice in", values, "oaordersettlementprice");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementpriceNotIn(List<BigDecimal> values) {
            addCriterion("OAOrderSettlementPrice not in", values, "oaordersettlementprice");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderSettlementPrice between", value1, value2, "oaordersettlementprice");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderSettlementPrice not between", value1, value2, "oaordersettlementprice");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementexchangerateIsNull() {
            addCriterion("OAOrderSettlementExchangeRate is null");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementexchangerateIsNotNull() {
            addCriterion("OAOrderSettlementExchangeRate is not null");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementexchangerateEqualTo(BigDecimal value) {
            addCriterion("OAOrderSettlementExchangeRate =", value, "oaordersettlementexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementexchangerateNotEqualTo(BigDecimal value) {
            addCriterion("OAOrderSettlementExchangeRate <>", value, "oaordersettlementexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementexchangerateGreaterThan(BigDecimal value) {
            addCriterion("OAOrderSettlementExchangeRate >", value, "oaordersettlementexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementexchangerateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderSettlementExchangeRate >=", value, "oaordersettlementexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementexchangerateLessThan(BigDecimal value) {
            addCriterion("OAOrderSettlementExchangeRate <", value, "oaordersettlementexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementexchangerateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderSettlementExchangeRate <=", value, "oaordersettlementexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementexchangerateIn(List<BigDecimal> values) {
            addCriterion("OAOrderSettlementExchangeRate in", values, "oaordersettlementexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementexchangerateNotIn(List<BigDecimal> values) {
            addCriterion("OAOrderSettlementExchangeRate not in", values, "oaordersettlementexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementexchangerateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderSettlementExchangeRate between", value1, value2, "oaordersettlementexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementexchangerateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderSettlementExchangeRate not between", value1, value2, "oaordersettlementexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementcurrencyidIsNull() {
            addCriterion("OAOrderSettlementCurrencyID is null");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementcurrencyidIsNotNull() {
            addCriterion("OAOrderSettlementCurrencyID is not null");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementcurrencyidEqualTo(Integer value) {
            addCriterion("OAOrderSettlementCurrencyID =", value, "oaordersettlementcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementcurrencyidNotEqualTo(Integer value) {
            addCriterion("OAOrderSettlementCurrencyID <>", value, "oaordersettlementcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementcurrencyidGreaterThan(Integer value) {
            addCriterion("OAOrderSettlementCurrencyID >", value, "oaordersettlementcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementcurrencyidGreaterThanOrEqualTo(Integer value) {
            addCriterion("OAOrderSettlementCurrencyID >=", value, "oaordersettlementcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementcurrencyidLessThan(Integer value) {
            addCriterion("OAOrderSettlementCurrencyID <", value, "oaordersettlementcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementcurrencyidLessThanOrEqualTo(Integer value) {
            addCriterion("OAOrderSettlementCurrencyID <=", value, "oaordersettlementcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementcurrencyidIn(List<Integer> values) {
            addCriterion("OAOrderSettlementCurrencyID in", values, "oaordersettlementcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementcurrencyidNotIn(List<Integer> values) {
            addCriterion("OAOrderSettlementCurrencyID not in", values, "oaordersettlementcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementcurrencyidBetween(Integer value1, Integer value2) {
            addCriterion("OAOrderSettlementCurrencyID between", value1, value2, "oaordersettlementcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementcurrencyidNotBetween(Integer value1, Integer value2) {
            addCriterion("OAOrderSettlementCurrencyID not between", value1, value2, "oaordersettlementcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceIsNull() {
            addCriterion("OAOrderBookingPrice is null");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceIsNotNull() {
            addCriterion("OAOrderBookingPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceEqualTo(BigDecimal value) {
            addCriterion("OAOrderBookingPrice =", value, "oaorderbookingprice");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceNotEqualTo(BigDecimal value) {
            addCriterion("OAOrderBookingPrice <>", value, "oaorderbookingprice");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceGreaterThan(BigDecimal value) {
            addCriterion("OAOrderBookingPrice >", value, "oaorderbookingprice");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderBookingPrice >=", value, "oaorderbookingprice");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceLessThan(BigDecimal value) {
            addCriterion("OAOrderBookingPrice <", value, "oaorderbookingprice");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderBookingPrice <=", value, "oaorderbookingprice");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceIn(List<BigDecimal> values) {
            addCriterion("OAOrderBookingPrice in", values, "oaorderbookingprice");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceNotIn(List<BigDecimal> values) {
            addCriterion("OAOrderBookingPrice not in", values, "oaorderbookingprice");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderBookingPrice between", value1, value2, "oaorderbookingprice");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderBookingPrice not between", value1, value2, "oaorderbookingprice");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpricecurrencyIsNull() {
            addCriterion("OAOrderBookingPriceCurrency is null");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpricecurrencyIsNotNull() {
            addCriterion("OAOrderBookingPriceCurrency is not null");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpricecurrencyEqualTo(Integer value) {
            addCriterion("OAOrderBookingPriceCurrency =", value, "oaorderbookingpricecurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpricecurrencyNotEqualTo(Integer value) {
            addCriterion("OAOrderBookingPriceCurrency <>", value, "oaorderbookingpricecurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpricecurrencyGreaterThan(Integer value) {
            addCriterion("OAOrderBookingPriceCurrency >", value, "oaorderbookingpricecurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpricecurrencyGreaterThanOrEqualTo(Integer value) {
            addCriterion("OAOrderBookingPriceCurrency >=", value, "oaorderbookingpricecurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpricecurrencyLessThan(Integer value) {
            addCriterion("OAOrderBookingPriceCurrency <", value, "oaorderbookingpricecurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpricecurrencyLessThanOrEqualTo(Integer value) {
            addCriterion("OAOrderBookingPriceCurrency <=", value, "oaorderbookingpricecurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpricecurrencyIn(List<Integer> values) {
            addCriterion("OAOrderBookingPriceCurrency in", values, "oaorderbookingpricecurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpricecurrencyNotIn(List<Integer> values) {
            addCriterion("OAOrderBookingPriceCurrency not in", values, "oaorderbookingpricecurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpricecurrencyBetween(Integer value1, Integer value2) {
            addCriterion("OAOrderBookingPriceCurrency between", value1, value2, "oaorderbookingpricecurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpricecurrencyNotBetween(Integer value1, Integer value2) {
            addCriterion("OAOrderBookingPriceCurrency not between", value1, value2, "oaorderbookingpricecurrency");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceexchangerateIsNull() {
            addCriterion("OAOrderBookingPriceExchangeRate is null");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceexchangerateIsNotNull() {
            addCriterion("OAOrderBookingPriceExchangeRate is not null");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceexchangerateEqualTo(BigDecimal value) {
            addCriterion("OAOrderBookingPriceExchangeRate =", value, "oaorderbookingpriceexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceexchangerateNotEqualTo(BigDecimal value) {
            addCriterion("OAOrderBookingPriceExchangeRate <>", value, "oaorderbookingpriceexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceexchangerateGreaterThan(BigDecimal value) {
            addCriterion("OAOrderBookingPriceExchangeRate >", value, "oaorderbookingpriceexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceexchangerateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderBookingPriceExchangeRate >=", value, "oaorderbookingpriceexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceexchangerateLessThan(BigDecimal value) {
            addCriterion("OAOrderBookingPriceExchangeRate <", value, "oaorderbookingpriceexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceexchangerateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderBookingPriceExchangeRate <=", value, "oaorderbookingpriceexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceexchangerateIn(List<BigDecimal> values) {
            addCriterion("OAOrderBookingPriceExchangeRate in", values, "oaorderbookingpriceexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceexchangerateNotIn(List<BigDecimal> values) {
            addCriterion("OAOrderBookingPriceExchangeRate not in", values, "oaorderbookingpriceexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceexchangerateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderBookingPriceExchangeRate between", value1, value2, "oaorderbookingpriceexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaorderbookingpriceexchangerateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderBookingPriceExchangeRate not between", value1, value2, "oaorderbookingpriceexchangerate");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceafterbaseIsNull() {
            addCriterion("OAOrderSellingPriceAfterBase is null");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceafterbaseIsNotNull() {
            addCriterion("OAOrderSellingPriceAfterBase is not null");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceafterbaseEqualTo(BigDecimal value) {
            addCriterion("OAOrderSellingPriceAfterBase =", value, "oaordersellingpriceafterbase");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceafterbaseNotEqualTo(BigDecimal value) {
            addCriterion("OAOrderSellingPriceAfterBase <>", value, "oaordersellingpriceafterbase");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceafterbaseGreaterThan(BigDecimal value) {
            addCriterion("OAOrderSellingPriceAfterBase >", value, "oaordersellingpriceafterbase");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceafterbaseGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderSellingPriceAfterBase >=", value, "oaordersellingpriceafterbase");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceafterbaseLessThan(BigDecimal value) {
            addCriterion("OAOrderSellingPriceAfterBase <", value, "oaordersellingpriceafterbase");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceafterbaseLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderSellingPriceAfterBase <=", value, "oaordersellingpriceafterbase");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceafterbaseIn(List<BigDecimal> values) {
            addCriterion("OAOrderSellingPriceAfterBase in", values, "oaordersellingpriceafterbase");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceafterbaseNotIn(List<BigDecimal> values) {
            addCriterion("OAOrderSellingPriceAfterBase not in", values, "oaordersellingpriceafterbase");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceafterbaseBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderSellingPriceAfterBase between", value1, value2, "oaordersellingpriceafterbase");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceafterbaseNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderSellingPriceAfterBase not between", value1, value2, "oaordersellingpriceafterbase");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceaftermblIsNull() {
            addCriterion("OAOrderSellingPriceAfterMBL is null");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceaftermblIsNotNull() {
            addCriterion("OAOrderSellingPriceAfterMBL is not null");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceaftermblEqualTo(BigDecimal value) {
            addCriterion("OAOrderSellingPriceAfterMBL =", value, "oaordersellingpriceaftermbl");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceaftermblNotEqualTo(BigDecimal value) {
            addCriterion("OAOrderSellingPriceAfterMBL <>", value, "oaordersellingpriceaftermbl");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceaftermblGreaterThan(BigDecimal value) {
            addCriterion("OAOrderSellingPriceAfterMBL >", value, "oaordersellingpriceaftermbl");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceaftermblGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderSellingPriceAfterMBL >=", value, "oaordersellingpriceaftermbl");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceaftermblLessThan(BigDecimal value) {
            addCriterion("OAOrderSellingPriceAfterMBL <", value, "oaordersellingpriceaftermbl");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceaftermblLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderSellingPriceAfterMBL <=", value, "oaordersellingpriceaftermbl");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceaftermblIn(List<BigDecimal> values) {
            addCriterion("OAOrderSellingPriceAfterMBL in", values, "oaordersellingpriceaftermbl");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceaftermblNotIn(List<BigDecimal> values) {
            addCriterion("OAOrderSellingPriceAfterMBL not in", values, "oaordersellingpriceaftermbl");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceaftermblBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderSellingPriceAfterMBL between", value1, value2, "oaordersellingpriceaftermbl");
            return (Criteria) this;
        }

        public Criteria andOaordersellingpriceaftermblNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderSellingPriceAfterMBL not between", value1, value2, "oaordersellingpriceaftermbl");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementmodelIsNull() {
            addCriterion("OAOrderSettlementModel is null");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementmodelIsNotNull() {
            addCriterion("OAOrderSettlementModel is not null");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementmodelEqualTo(Integer value) {
            addCriterion("OAOrderSettlementModel =", value, "oaordersettlementmodel");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementmodelNotEqualTo(Integer value) {
            addCriterion("OAOrderSettlementModel <>", value, "oaordersettlementmodel");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementmodelGreaterThan(Integer value) {
            addCriterion("OAOrderSettlementModel >", value, "oaordersettlementmodel");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementmodelGreaterThanOrEqualTo(Integer value) {
            addCriterion("OAOrderSettlementModel >=", value, "oaordersettlementmodel");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementmodelLessThan(Integer value) {
            addCriterion("OAOrderSettlementModel <", value, "oaordersettlementmodel");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementmodelLessThanOrEqualTo(Integer value) {
            addCriterion("OAOrderSettlementModel <=", value, "oaordersettlementmodel");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementmodelIn(List<Integer> values) {
            addCriterion("OAOrderSettlementModel in", values, "oaordersettlementmodel");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementmodelNotIn(List<Integer> values) {
            addCriterion("OAOrderSettlementModel not in", values, "oaordersettlementmodel");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementmodelBetween(Integer value1, Integer value2) {
            addCriterion("OAOrderSettlementModel between", value1, value2, "oaordersettlementmodel");
            return (Criteria) this;
        }

        public Criteria andOaordersettlementmodelNotBetween(Integer value1, Integer value2) {
            addCriterion("OAOrderSettlementModel not between", value1, value2, "oaordersettlementmodel");
            return (Criteria) this;
        }

        public Criteria andOaorderdistributorsettlementamountIsNull() {
            addCriterion("OAOrderDistributorSettlementAmount is null");
            return (Criteria) this;
        }

        public Criteria andOaorderdistributorsettlementamountIsNotNull() {
            addCriterion("OAOrderDistributorSettlementAmount is not null");
            return (Criteria) this;
        }

        public Criteria andOaorderdistributorsettlementamountEqualTo(BigDecimal value) {
            addCriterion("OAOrderDistributorSettlementAmount =", value, "oaorderdistributorsettlementamount");
            return (Criteria) this;
        }

        public Criteria andOaorderdistributorsettlementamountNotEqualTo(BigDecimal value) {
            addCriterion("OAOrderDistributorSettlementAmount <>", value, "oaorderdistributorsettlementamount");
            return (Criteria) this;
        }

        public Criteria andOaorderdistributorsettlementamountGreaterThan(BigDecimal value) {
            addCriterion("OAOrderDistributorSettlementAmount >", value, "oaorderdistributorsettlementamount");
            return (Criteria) this;
        }

        public Criteria andOaorderdistributorsettlementamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderDistributorSettlementAmount >=", value, "oaorderdistributorsettlementamount");
            return (Criteria) this;
        }

        public Criteria andOaorderdistributorsettlementamountLessThan(BigDecimal value) {
            addCriterion("OAOrderDistributorSettlementAmount <", value, "oaorderdistributorsettlementamount");
            return (Criteria) this;
        }

        public Criteria andOaorderdistributorsettlementamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOrderDistributorSettlementAmount <=", value, "oaorderdistributorsettlementamount");
            return (Criteria) this;
        }

        public Criteria andOaorderdistributorsettlementamountIn(List<BigDecimal> values) {
            addCriterion("OAOrderDistributorSettlementAmount in", values, "oaorderdistributorsettlementamount");
            return (Criteria) this;
        }

        public Criteria andOaorderdistributorsettlementamountNotIn(List<BigDecimal> values) {
            addCriterion("OAOrderDistributorSettlementAmount not in", values, "oaorderdistributorsettlementamount");
            return (Criteria) this;
        }

        public Criteria andOaorderdistributorsettlementamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderDistributorSettlementAmount between", value1, value2, "oaorderdistributorsettlementamount");
            return (Criteria) this;
        }

        public Criteria andOaorderdistributorsettlementamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOrderDistributorSettlementAmount not between", value1, value2, "oaorderdistributorsettlementamount");
            return (Criteria) this;
        }

        public Criteria andOafloatingrateIsNull() {
            addCriterion("OAFloatingRate is null");
            return (Criteria) this;
        }

        public Criteria andOafloatingrateIsNotNull() {
            addCriterion("OAFloatingRate is not null");
            return (Criteria) this;
        }

        public Criteria andOafloatingrateEqualTo(BigDecimal value) {
            addCriterion("OAFloatingRate =", value, "oafloatingrate");
            return (Criteria) this;
        }

        public Criteria andOafloatingrateNotEqualTo(BigDecimal value) {
            addCriterion("OAFloatingRate <>", value, "oafloatingrate");
            return (Criteria) this;
        }

        public Criteria andOafloatingrateGreaterThan(BigDecimal value) {
            addCriterion("OAFloatingRate >", value, "oafloatingrate");
            return (Criteria) this;
        }

        public Criteria andOafloatingrateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAFloatingRate >=", value, "oafloatingrate");
            return (Criteria) this;
        }

        public Criteria andOafloatingrateLessThan(BigDecimal value) {
            addCriterion("OAFloatingRate <", value, "oafloatingrate");
            return (Criteria) this;
        }

        public Criteria andOafloatingrateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAFloatingRate <=", value, "oafloatingrate");
            return (Criteria) this;
        }

        public Criteria andOafloatingrateIn(List<BigDecimal> values) {
            addCriterion("OAFloatingRate in", values, "oafloatingrate");
            return (Criteria) this;
        }

        public Criteria andOafloatingrateNotIn(List<BigDecimal> values) {
            addCriterion("OAFloatingRate not in", values, "oafloatingrate");
            return (Criteria) this;
        }

        public Criteria andOafloatingrateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAFloatingRate between", value1, value2, "oafloatingrate");
            return (Criteria) this;
        }

        public Criteria andOafloatingrateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAFloatingRate not between", value1, value2, "oafloatingrate");
            return (Criteria) this;
        }

        public Criteria andOaadjustpriceIsNull() {
            addCriterion("OAAdjustPrice is null");
            return (Criteria) this;
        }

        public Criteria andOaadjustpriceIsNotNull() {
            addCriterion("OAAdjustPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOaadjustpriceEqualTo(BigDecimal value) {
            addCriterion("OAAdjustPrice =", value, "oaadjustprice");
            return (Criteria) this;
        }

        public Criteria andOaadjustpriceNotEqualTo(BigDecimal value) {
            addCriterion("OAAdjustPrice <>", value, "oaadjustprice");
            return (Criteria) this;
        }

        public Criteria andOaadjustpriceGreaterThan(BigDecimal value) {
            addCriterion("OAAdjustPrice >", value, "oaadjustprice");
            return (Criteria) this;
        }

        public Criteria andOaadjustpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAAdjustPrice >=", value, "oaadjustprice");
            return (Criteria) this;
        }

        public Criteria andOaadjustpriceLessThan(BigDecimal value) {
            addCriterion("OAAdjustPrice <", value, "oaadjustprice");
            return (Criteria) this;
        }

        public Criteria andOaadjustpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAAdjustPrice <=", value, "oaadjustprice");
            return (Criteria) this;
        }

        public Criteria andOaadjustpriceIn(List<BigDecimal> values) {
            addCriterion("OAAdjustPrice in", values, "oaadjustprice");
            return (Criteria) this;
        }

        public Criteria andOaadjustpriceNotIn(List<BigDecimal> values) {
            addCriterion("OAAdjustPrice not in", values, "oaadjustprice");
            return (Criteria) this;
        }

        public Criteria andOaadjustpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAAdjustPrice between", value1, value2, "oaadjustprice");
            return (Criteria) this;
        }

        public Criteria andOaadjustpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAAdjustPrice not between", value1, value2, "oaadjustprice");
            return (Criteria) this;
        }

        public Criteria andOanbadjustpriceIsNull() {
            addCriterion("OANBAdjustPrice is null");
            return (Criteria) this;
        }

        public Criteria andOanbadjustpriceIsNotNull() {
            addCriterion("OANBAdjustPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOanbadjustpriceEqualTo(BigDecimal value) {
            addCriterion("OANBAdjustPrice =", value, "oanbadjustprice");
            return (Criteria) this;
        }

        public Criteria andOanbadjustpriceNotEqualTo(BigDecimal value) {
            addCriterion("OANBAdjustPrice <>", value, "oanbadjustprice");
            return (Criteria) this;
        }

        public Criteria andOanbadjustpriceGreaterThan(BigDecimal value) {
            addCriterion("OANBAdjustPrice >", value, "oanbadjustprice");
            return (Criteria) this;
        }

        public Criteria andOanbadjustpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OANBAdjustPrice >=", value, "oanbadjustprice");
            return (Criteria) this;
        }

        public Criteria andOanbadjustpriceLessThan(BigDecimal value) {
            addCriterion("OANBAdjustPrice <", value, "oanbadjustprice");
            return (Criteria) this;
        }

        public Criteria andOanbadjustpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OANBAdjustPrice <=", value, "oanbadjustprice");
            return (Criteria) this;
        }

        public Criteria andOanbadjustpriceIn(List<BigDecimal> values) {
            addCriterion("OANBAdjustPrice in", values, "oanbadjustprice");
            return (Criteria) this;
        }

        public Criteria andOanbadjustpriceNotIn(List<BigDecimal> values) {
            addCriterion("OANBAdjustPrice not in", values, "oanbadjustprice");
            return (Criteria) this;
        }

        public Criteria andOanbadjustpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OANBAdjustPrice between", value1, value2, "oanbadjustprice");
            return (Criteria) this;
        }

        public Criteria andOanbadjustpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OANBAdjustPrice not between", value1, value2, "oanbadjustprice");
            return (Criteria) this;
        }

        public Criteria andOaroomtotalbeforepricingIsNull() {
            addCriterion("OARoomTotalBeforePricing is null");
            return (Criteria) this;
        }

        public Criteria andOaroomtotalbeforepricingIsNotNull() {
            addCriterion("OARoomTotalBeforePricing is not null");
            return (Criteria) this;
        }

        public Criteria andOaroomtotalbeforepricingEqualTo(BigDecimal value) {
            addCriterion("OARoomTotalBeforePricing =", value, "oaroomtotalbeforepricing");
            return (Criteria) this;
        }

        public Criteria andOaroomtotalbeforepricingNotEqualTo(BigDecimal value) {
            addCriterion("OARoomTotalBeforePricing <>", value, "oaroomtotalbeforepricing");
            return (Criteria) this;
        }

        public Criteria andOaroomtotalbeforepricingGreaterThan(BigDecimal value) {
            addCriterion("OARoomTotalBeforePricing >", value, "oaroomtotalbeforepricing");
            return (Criteria) this;
        }

        public Criteria andOaroomtotalbeforepricingGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OARoomTotalBeforePricing >=", value, "oaroomtotalbeforepricing");
            return (Criteria) this;
        }

        public Criteria andOaroomtotalbeforepricingLessThan(BigDecimal value) {
            addCriterion("OARoomTotalBeforePricing <", value, "oaroomtotalbeforepricing");
            return (Criteria) this;
        }

        public Criteria andOaroomtotalbeforepricingLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OARoomTotalBeforePricing <=", value, "oaroomtotalbeforepricing");
            return (Criteria) this;
        }

        public Criteria andOaroomtotalbeforepricingIn(List<BigDecimal> values) {
            addCriterion("OARoomTotalBeforePricing in", values, "oaroomtotalbeforepricing");
            return (Criteria) this;
        }

        public Criteria andOaroomtotalbeforepricingNotIn(List<BigDecimal> values) {
            addCriterion("OARoomTotalBeforePricing not in", values, "oaroomtotalbeforepricing");
            return (Criteria) this;
        }

        public Criteria andOaroomtotalbeforepricingBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OARoomTotalBeforePricing between", value1, value2, "oaroomtotalbeforepricing");
            return (Criteria) this;
        }

        public Criteria andOaroomtotalbeforepricingNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OARoomTotalBeforePricing not between", value1, value2, "oaroomtotalbeforepricing");
            return (Criteria) this;
        }

        public Criteria andOaprimitivepriceIsNull() {
            addCriterion("OAPrimitivePrice is null");
            return (Criteria) this;
        }

        public Criteria andOaprimitivepriceIsNotNull() {
            addCriterion("OAPrimitivePrice is not null");
            return (Criteria) this;
        }

        public Criteria andOaprimitivepriceEqualTo(BigDecimal value) {
            addCriterion("OAPrimitivePrice =", value, "oaprimitiveprice");
            return (Criteria) this;
        }

        public Criteria andOaprimitivepriceNotEqualTo(BigDecimal value) {
            addCriterion("OAPrimitivePrice <>", value, "oaprimitiveprice");
            return (Criteria) this;
        }

        public Criteria andOaprimitivepriceGreaterThan(BigDecimal value) {
            addCriterion("OAPrimitivePrice >", value, "oaprimitiveprice");
            return (Criteria) this;
        }

        public Criteria andOaprimitivepriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAPrimitivePrice >=", value, "oaprimitiveprice");
            return (Criteria) this;
        }

        public Criteria andOaprimitivepriceLessThan(BigDecimal value) {
            addCriterion("OAPrimitivePrice <", value, "oaprimitiveprice");
            return (Criteria) this;
        }

        public Criteria andOaprimitivepriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAPrimitivePrice <=", value, "oaprimitiveprice");
            return (Criteria) this;
        }

        public Criteria andOaprimitivepriceIn(List<BigDecimal> values) {
            addCriterion("OAPrimitivePrice in", values, "oaprimitiveprice");
            return (Criteria) this;
        }

        public Criteria andOaprimitivepriceNotIn(List<BigDecimal> values) {
            addCriterion("OAPrimitivePrice not in", values, "oaprimitiveprice");
            return (Criteria) this;
        }

        public Criteria andOaprimitivepriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAPrimitivePrice between", value1, value2, "oaprimitiveprice");
            return (Criteria) this;
        }

        public Criteria andOaprimitivepriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAPrimitivePrice not between", value1, value2, "oaprimitiveprice");
            return (Criteria) this;
        }

        public Criteria andOaotaoriginalpriceIsNull() {
            addCriterion("OAOTAOriginalPrice is null");
            return (Criteria) this;
        }

        public Criteria andOaotaoriginalpriceIsNotNull() {
            addCriterion("OAOTAOriginalPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOaotaoriginalpriceEqualTo(BigDecimal value) {
            addCriterion("OAOTAOriginalPrice =", value, "oaotaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaotaoriginalpriceNotEqualTo(BigDecimal value) {
            addCriterion("OAOTAOriginalPrice <>", value, "oaotaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaotaoriginalpriceGreaterThan(BigDecimal value) {
            addCriterion("OAOTAOriginalPrice >", value, "oaotaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaotaoriginalpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOTAOriginalPrice >=", value, "oaotaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaotaoriginalpriceLessThan(BigDecimal value) {
            addCriterion("OAOTAOriginalPrice <", value, "oaotaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaotaoriginalpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOTAOriginalPrice <=", value, "oaotaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaotaoriginalpriceIn(List<BigDecimal> values) {
            addCriterion("OAOTAOriginalPrice in", values, "oaotaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaotaoriginalpriceNotIn(List<BigDecimal> values) {
            addCriterion("OAOTAOriginalPrice not in", values, "oaotaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaotaoriginalpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOTAOriginalPrice between", value1, value2, "oaotaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaotaoriginalpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOTAOriginalPrice not between", value1, value2, "oaotaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOabasesalepriceIsNull() {
            addCriterion("OABaseSalePrice is null");
            return (Criteria) this;
        }

        public Criteria andOabasesalepriceIsNotNull() {
            addCriterion("OABaseSalePrice is not null");
            return (Criteria) this;
        }

        public Criteria andOabasesalepriceEqualTo(BigDecimal value) {
            addCriterion("OABaseSalePrice =", value, "oabasesaleprice");
            return (Criteria) this;
        }

        public Criteria andOabasesalepriceNotEqualTo(BigDecimal value) {
            addCriterion("OABaseSalePrice <>", value, "oabasesaleprice");
            return (Criteria) this;
        }

        public Criteria andOabasesalepriceGreaterThan(BigDecimal value) {
            addCriterion("OABaseSalePrice >", value, "oabasesaleprice");
            return (Criteria) this;
        }

        public Criteria andOabasesalepriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OABaseSalePrice >=", value, "oabasesaleprice");
            return (Criteria) this;
        }

        public Criteria andOabasesalepriceLessThan(BigDecimal value) {
            addCriterion("OABaseSalePrice <", value, "oabasesaleprice");
            return (Criteria) this;
        }

        public Criteria andOabasesalepriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OABaseSalePrice <=", value, "oabasesaleprice");
            return (Criteria) this;
        }

        public Criteria andOabasesalepriceIn(List<BigDecimal> values) {
            addCriterion("OABaseSalePrice in", values, "oabasesaleprice");
            return (Criteria) this;
        }

        public Criteria andOabasesalepriceNotIn(List<BigDecimal> values) {
            addCriterion("OABaseSalePrice not in", values, "oabasesaleprice");
            return (Criteria) this;
        }

        public Criteria andOabasesalepriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OABaseSalePrice between", value1, value2, "oabasesaleprice");
            return (Criteria) this;
        }

        public Criteria andOabasesalepriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OABaseSalePrice not between", value1, value2, "oabasesaleprice");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforecouponIsNull() {
            addCriterion("OASalePriceBeforeCoupon is null");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforecouponIsNotNull() {
            addCriterion("OASalePriceBeforeCoupon is not null");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforecouponEqualTo(BigDecimal value) {
            addCriterion("OASalePriceBeforeCoupon =", value, "oasalepricebeforecoupon");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforecouponNotEqualTo(BigDecimal value) {
            addCriterion("OASalePriceBeforeCoupon <>", value, "oasalepricebeforecoupon");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforecouponGreaterThan(BigDecimal value) {
            addCriterion("OASalePriceBeforeCoupon >", value, "oasalepricebeforecoupon");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforecouponGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OASalePriceBeforeCoupon >=", value, "oasalepricebeforecoupon");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforecouponLessThan(BigDecimal value) {
            addCriterion("OASalePriceBeforeCoupon <", value, "oasalepricebeforecoupon");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforecouponLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OASalePriceBeforeCoupon <=", value, "oasalepricebeforecoupon");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforecouponIn(List<BigDecimal> values) {
            addCriterion("OASalePriceBeforeCoupon in", values, "oasalepricebeforecoupon");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforecouponNotIn(List<BigDecimal> values) {
            addCriterion("OASalePriceBeforeCoupon not in", values, "oasalepricebeforecoupon");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforecouponBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OASalePriceBeforeCoupon between", value1, value2, "oasalepricebeforecoupon");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforecouponNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OASalePriceBeforeCoupon not between", value1, value2, "oasalepricebeforecoupon");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforebiddingIsNull() {
            addCriterion("OASalePriceBeforeBidding is null");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforebiddingIsNotNull() {
            addCriterion("OASalePriceBeforeBidding is not null");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforebiddingEqualTo(BigDecimal value) {
            addCriterion("OASalePriceBeforeBidding =", value, "oasalepricebeforebidding");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforebiddingNotEqualTo(BigDecimal value) {
            addCriterion("OASalePriceBeforeBidding <>", value, "oasalepricebeforebidding");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforebiddingGreaterThan(BigDecimal value) {
            addCriterion("OASalePriceBeforeBidding >", value, "oasalepricebeforebidding");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforebiddingGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OASalePriceBeforeBidding >=", value, "oasalepricebeforebidding");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforebiddingLessThan(BigDecimal value) {
            addCriterion("OASalePriceBeforeBidding <", value, "oasalepricebeforebidding");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforebiddingLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OASalePriceBeforeBidding <=", value, "oasalepricebeforebidding");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforebiddingIn(List<BigDecimal> values) {
            addCriterion("OASalePriceBeforeBidding in", values, "oasalepricebeforebidding");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforebiddingNotIn(List<BigDecimal> values) {
            addCriterion("OASalePriceBeforeBidding not in", values, "oasalepricebeforebidding");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforebiddingBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OASalePriceBeforeBidding between", value1, value2, "oasalepricebeforebidding");
            return (Criteria) this;
        }

        public Criteria andOasalepricebeforebiddingNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OASalePriceBeforeBidding not between", value1, value2, "oasalepricebeforebidding");
            return (Criteria) this;
        }

        public Criteria andOaoriginalpriceIsNull() {
            addCriterion("OAOriginalPrice is null");
            return (Criteria) this;
        }

        public Criteria andOaoriginalpriceIsNotNull() {
            addCriterion("OAOriginalPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOaoriginalpriceEqualTo(BigDecimal value) {
            addCriterion("OAOriginalPrice =", value, "oaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaoriginalpriceNotEqualTo(BigDecimal value) {
            addCriterion("OAOriginalPrice <>", value, "oaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaoriginalpriceGreaterThan(BigDecimal value) {
            addCriterion("OAOriginalPrice >", value, "oaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaoriginalpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOriginalPrice >=", value, "oaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaoriginalpriceLessThan(BigDecimal value) {
            addCriterion("OAOriginalPrice <", value, "oaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaoriginalpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAOriginalPrice <=", value, "oaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaoriginalpriceIn(List<BigDecimal> values) {
            addCriterion("OAOriginalPrice in", values, "oaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaoriginalpriceNotIn(List<BigDecimal> values) {
            addCriterion("OAOriginalPrice not in", values, "oaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaoriginalpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOriginalPrice between", value1, value2, "oaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOaoriginalpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAOriginalPrice not between", value1, value2, "oaoriginalprice");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoIsNull() {
            addCriterion("OACashExpensesInfo is null");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoIsNotNull() {
            addCriterion("OACashExpensesInfo is not null");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoEqualTo(String value) {
            addCriterion("OACashExpensesInfo =", value, "oacashexpensesinfo");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoNotEqualTo(String value) {
            addCriterion("OACashExpensesInfo <>", value, "oacashexpensesinfo");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoGreaterThan(String value) {
            addCriterion("OACashExpensesInfo >", value, "oacashexpensesinfo");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoGreaterThanOrEqualTo(String value) {
            addCriterion("OACashExpensesInfo >=", value, "oacashexpensesinfo");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoLessThan(String value) {
            addCriterion("OACashExpensesInfo <", value, "oacashexpensesinfo");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoLessThanOrEqualTo(String value) {
            addCriterion("OACashExpensesInfo <=", value, "oacashexpensesinfo");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoLike(String value) {
            addCriterion("OACashExpensesInfo like", value, "oacashexpensesinfo");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoNotLike(String value) {
            addCriterion("OACashExpensesInfo not like", value, "oacashexpensesinfo");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoIn(List<String> values) {
            addCriterion("OACashExpensesInfo in", values, "oacashexpensesinfo");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoNotIn(List<String> values) {
            addCriterion("OACashExpensesInfo not in", values, "oacashexpensesinfo");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoBetween(String value1, String value2) {
            addCriterion("OACashExpensesInfo between", value1, value2, "oacashexpensesinfo");
            return (Criteria) this;
        }

        public Criteria andOacashexpensesinfoNotBetween(String value1, String value2) {
            addCriterion("OACashExpensesInfo not between", value1, value2, "oacashexpensesinfo");
            return (Criteria) this;
        }

        public Criteria andOapromoriskamountIsNull() {
            addCriterion("OAPromoRiskAmount is null");
            return (Criteria) this;
        }

        public Criteria andOapromoriskamountIsNotNull() {
            addCriterion("OAPromoRiskAmount is not null");
            return (Criteria) this;
        }

        public Criteria andOapromoriskamountEqualTo(BigDecimal value) {
            addCriterion("OAPromoRiskAmount =", value, "oapromoriskamount");
            return (Criteria) this;
        }

        public Criteria andOapromoriskamountNotEqualTo(BigDecimal value) {
            addCriterion("OAPromoRiskAmount <>", value, "oapromoriskamount");
            return (Criteria) this;
        }

        public Criteria andOapromoriskamountGreaterThan(BigDecimal value) {
            addCriterion("OAPromoRiskAmount >", value, "oapromoriskamount");
            return (Criteria) this;
        }

        public Criteria andOapromoriskamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAPromoRiskAmount >=", value, "oapromoriskamount");
            return (Criteria) this;
        }

        public Criteria andOapromoriskamountLessThan(BigDecimal value) {
            addCriterion("OAPromoRiskAmount <", value, "oapromoriskamount");
            return (Criteria) this;
        }

        public Criteria andOapromoriskamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAPromoRiskAmount <=", value, "oapromoriskamount");
            return (Criteria) this;
        }

        public Criteria andOapromoriskamountIn(List<BigDecimal> values) {
            addCriterion("OAPromoRiskAmount in", values, "oapromoriskamount");
            return (Criteria) this;
        }

        public Criteria andOapromoriskamountNotIn(List<BigDecimal> values) {
            addCriterion("OAPromoRiskAmount not in", values, "oapromoriskamount");
            return (Criteria) this;
        }

        public Criteria andOapromoriskamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAPromoRiskAmount between", value1, value2, "oapromoriskamount");
            return (Criteria) this;
        }

        public Criteria andOapromoriskamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAPromoRiskAmount not between", value1, value2, "oapromoriskamount");
            return (Criteria) this;
        }

        public Criteria andOamblbeatadjustpriceIsNull() {
            addCriterion("OAMBLBeatAdjustPrice is null");
            return (Criteria) this;
        }

        public Criteria andOamblbeatadjustpriceIsNotNull() {
            addCriterion("OAMBLBeatAdjustPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOamblbeatadjustpriceEqualTo(BigDecimal value) {
            addCriterion("OAMBLBeatAdjustPrice =", value, "oamblbeatadjustprice");
            return (Criteria) this;
        }

        public Criteria andOamblbeatadjustpriceNotEqualTo(BigDecimal value) {
            addCriterion("OAMBLBeatAdjustPrice <>", value, "oamblbeatadjustprice");
            return (Criteria) this;
        }

        public Criteria andOamblbeatadjustpriceGreaterThan(BigDecimal value) {
            addCriterion("OAMBLBeatAdjustPrice >", value, "oamblbeatadjustprice");
            return (Criteria) this;
        }

        public Criteria andOamblbeatadjustpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OAMBLBeatAdjustPrice >=", value, "oamblbeatadjustprice");
            return (Criteria) this;
        }

        public Criteria andOamblbeatadjustpriceLessThan(BigDecimal value) {
            addCriterion("OAMBLBeatAdjustPrice <", value, "oamblbeatadjustprice");
            return (Criteria) this;
        }

        public Criteria andOamblbeatadjustpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OAMBLBeatAdjustPrice <=", value, "oamblbeatadjustprice");
            return (Criteria) this;
        }

        public Criteria andOamblbeatadjustpriceIn(List<BigDecimal> values) {
            addCriterion("OAMBLBeatAdjustPrice in", values, "oamblbeatadjustprice");
            return (Criteria) this;
        }

        public Criteria andOamblbeatadjustpriceNotIn(List<BigDecimal> values) {
            addCriterion("OAMBLBeatAdjustPrice not in", values, "oamblbeatadjustprice");
            return (Criteria) this;
        }

        public Criteria andOamblbeatadjustpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAMBLBeatAdjustPrice between", value1, value2, "oamblbeatadjustprice");
            return (Criteria) this;
        }

        public Criteria andOamblbeatadjustpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OAMBLBeatAdjustPrice not between", value1, value2, "oamblbeatadjustprice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderAmount
     *
     * @mbggenerated do_not_delete_during_merge Thu Feb 21 12:04:24 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderAmount
     *
     * @mbggenerated Thu Feb 21 12:04:24 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}