package com.adam.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderRequestSupplierLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    public OrderRequestSupplierLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrslrequestapiidIsNull() {
            addCriterion("ORSLRequestAPIID is null");
            return (Criteria) this;
        }

        public Criteria andOrslrequestapiidIsNotNull() {
            addCriterion("ORSLRequestAPIID is not null");
            return (Criteria) this;
        }

        public Criteria andOrslrequestapiidEqualTo(Integer value) {
            addCriterion("ORSLRequestAPIID =", value, "orslrequestapiid");
            return (Criteria) this;
        }

        public Criteria andOrslrequestapiidNotEqualTo(Integer value) {
            addCriterion("ORSLRequestAPIID <>", value, "orslrequestapiid");
            return (Criteria) this;
        }

        public Criteria andOrslrequestapiidGreaterThan(Integer value) {
            addCriterion("ORSLRequestAPIID >", value, "orslrequestapiid");
            return (Criteria) this;
        }

        public Criteria andOrslrequestapiidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORSLRequestAPIID >=", value, "orslrequestapiid");
            return (Criteria) this;
        }

        public Criteria andOrslrequestapiidLessThan(Integer value) {
            addCriterion("ORSLRequestAPIID <", value, "orslrequestapiid");
            return (Criteria) this;
        }

        public Criteria andOrslrequestapiidLessThanOrEqualTo(Integer value) {
            addCriterion("ORSLRequestAPIID <=", value, "orslrequestapiid");
            return (Criteria) this;
        }

        public Criteria andOrslrequestapiidIn(List<Integer> values) {
            addCriterion("ORSLRequestAPIID in", values, "orslrequestapiid");
            return (Criteria) this;
        }

        public Criteria andOrslrequestapiidNotIn(List<Integer> values) {
            addCriterion("ORSLRequestAPIID not in", values, "orslrequestapiid");
            return (Criteria) this;
        }

        public Criteria andOrslrequestapiidBetween(Integer value1, Integer value2) {
            addCriterion("ORSLRequestAPIID between", value1, value2, "orslrequestapiid");
            return (Criteria) this;
        }

        public Criteria andOrslrequestapiidNotBetween(Integer value1, Integer value2) {
            addCriterion("ORSLRequestAPIID not between", value1, value2, "orslrequestapiid");
            return (Criteria) this;
        }

        public Criteria andOrslrequestonIsNull() {
            addCriterion("ORSLRequestOn is null");
            return (Criteria) this;
        }

        public Criteria andOrslrequestonIsNotNull() {
            addCriterion("ORSLRequestOn is not null");
            return (Criteria) this;
        }

        public Criteria andOrslrequestonEqualTo(Date value) {
            addCriterion("ORSLRequestOn =", value, "orslrequeston");
            return (Criteria) this;
        }

        public Criteria andOrslrequestonNotEqualTo(Date value) {
            addCriterion("ORSLRequestOn <>", value, "orslrequeston");
            return (Criteria) this;
        }

        public Criteria andOrslrequestonGreaterThan(Date value) {
            addCriterion("ORSLRequestOn >", value, "orslrequeston");
            return (Criteria) this;
        }

        public Criteria andOrslrequestonGreaterThanOrEqualTo(Date value) {
            addCriterion("ORSLRequestOn >=", value, "orslrequeston");
            return (Criteria) this;
        }

        public Criteria andOrslrequestonLessThan(Date value) {
            addCriterion("ORSLRequestOn <", value, "orslrequeston");
            return (Criteria) this;
        }

        public Criteria andOrslrequestonLessThanOrEqualTo(Date value) {
            addCriterion("ORSLRequestOn <=", value, "orslrequeston");
            return (Criteria) this;
        }

        public Criteria andOrslrequestonIn(List<Date> values) {
            addCriterion("ORSLRequestOn in", values, "orslrequeston");
            return (Criteria) this;
        }

        public Criteria andOrslrequestonNotIn(List<Date> values) {
            addCriterion("ORSLRequestOn not in", values, "orslrequeston");
            return (Criteria) this;
        }

        public Criteria andOrslrequestonBetween(Date value1, Date value2) {
            addCriterion("ORSLRequestOn between", value1, value2, "orslrequeston");
            return (Criteria) this;
        }

        public Criteria andOrslrequestonNotBetween(Date value1, Date value2) {
            addCriterion("ORSLRequestOn not between", value1, value2, "orslrequeston");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentIsNull() {
            addCriterion("ORSLRequestContent is null");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentIsNotNull() {
            addCriterion("ORSLRequestContent is not null");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentEqualTo(String value) {
            addCriterion("ORSLRequestContent =", value, "orslrequestcontent");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentNotEqualTo(String value) {
            addCriterion("ORSLRequestContent <>", value, "orslrequestcontent");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentGreaterThan(String value) {
            addCriterion("ORSLRequestContent >", value, "orslrequestcontent");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentGreaterThanOrEqualTo(String value) {
            addCriterion("ORSLRequestContent >=", value, "orslrequestcontent");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentLessThan(String value) {
            addCriterion("ORSLRequestContent <", value, "orslrequestcontent");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentLessThanOrEqualTo(String value) {
            addCriterion("ORSLRequestContent <=", value, "orslrequestcontent");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentLike(String value) {
            addCriterion("ORSLRequestContent like", value, "orslrequestcontent");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentNotLike(String value) {
            addCriterion("ORSLRequestContent not like", value, "orslrequestcontent");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentIn(List<String> values) {
            addCriterion("ORSLRequestContent in", values, "orslrequestcontent");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentNotIn(List<String> values) {
            addCriterion("ORSLRequestContent not in", values, "orslrequestcontent");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentBetween(String value1, String value2) {
            addCriterion("ORSLRequestContent between", value1, value2, "orslrequestcontent");
            return (Criteria) this;
        }

        public Criteria andOrslrequestcontentNotBetween(String value1, String value2) {
            addCriterion("ORSLRequestContent not between", value1, value2, "orslrequestcontent");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentIsNull() {
            addCriterion("ORSLResponseContent is null");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentIsNotNull() {
            addCriterion("ORSLResponseContent is not null");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentEqualTo(String value) {
            addCriterion("ORSLResponseContent =", value, "orslresponsecontent");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentNotEqualTo(String value) {
            addCriterion("ORSLResponseContent <>", value, "orslresponsecontent");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentGreaterThan(String value) {
            addCriterion("ORSLResponseContent >", value, "orslresponsecontent");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentGreaterThanOrEqualTo(String value) {
            addCriterion("ORSLResponseContent >=", value, "orslresponsecontent");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentLessThan(String value) {
            addCriterion("ORSLResponseContent <", value, "orslresponsecontent");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentLessThanOrEqualTo(String value) {
            addCriterion("ORSLResponseContent <=", value, "orslresponsecontent");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentLike(String value) {
            addCriterion("ORSLResponseContent like", value, "orslresponsecontent");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentNotLike(String value) {
            addCriterion("ORSLResponseContent not like", value, "orslresponsecontent");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentIn(List<String> values) {
            addCriterion("ORSLResponseContent in", values, "orslresponsecontent");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentNotIn(List<String> values) {
            addCriterion("ORSLResponseContent not in", values, "orslresponsecontent");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentBetween(String value1, String value2) {
            addCriterion("ORSLResponseContent between", value1, value2, "orslresponsecontent");
            return (Criteria) this;
        }

        public Criteria andOrslresponsecontentNotBetween(String value1, String value2) {
            addCriterion("ORSLResponseContent not between", value1, value2, "orslresponsecontent");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameIsNull() {
            addCriterion("ORSLTriggerName is null");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameIsNotNull() {
            addCriterion("ORSLTriggerName is not null");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameEqualTo(String value) {
            addCriterion("ORSLTriggerName =", value, "orsltriggername");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameNotEqualTo(String value) {
            addCriterion("ORSLTriggerName <>", value, "orsltriggername");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameGreaterThan(String value) {
            addCriterion("ORSLTriggerName >", value, "orsltriggername");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameGreaterThanOrEqualTo(String value) {
            addCriterion("ORSLTriggerName >=", value, "orsltriggername");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameLessThan(String value) {
            addCriterion("ORSLTriggerName <", value, "orsltriggername");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameLessThanOrEqualTo(String value) {
            addCriterion("ORSLTriggerName <=", value, "orsltriggername");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameLike(String value) {
            addCriterion("ORSLTriggerName like", value, "orsltriggername");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameNotLike(String value) {
            addCriterion("ORSLTriggerName not like", value, "orsltriggername");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameIn(List<String> values) {
            addCriterion("ORSLTriggerName in", values, "orsltriggername");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameNotIn(List<String> values) {
            addCriterion("ORSLTriggerName not in", values, "orsltriggername");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameBetween(String value1, String value2) {
            addCriterion("ORSLTriggerName between", value1, value2, "orsltriggername");
            return (Criteria) this;
        }

        public Criteria andOrsltriggernameNotBetween(String value1, String value2) {
            addCriterion("ORSLTriggerName not between", value1, value2, "orsltriggername");
            return (Criteria) this;
        }

        public Criteria andOrslremarkIsNull() {
            addCriterion("ORSLRemark is null");
            return (Criteria) this;
        }

        public Criteria andOrslremarkIsNotNull() {
            addCriterion("ORSLRemark is not null");
            return (Criteria) this;
        }

        public Criteria andOrslremarkEqualTo(String value) {
            addCriterion("ORSLRemark =", value, "orslremark");
            return (Criteria) this;
        }

        public Criteria andOrslremarkNotEqualTo(String value) {
            addCriterion("ORSLRemark <>", value, "orslremark");
            return (Criteria) this;
        }

        public Criteria andOrslremarkGreaterThan(String value) {
            addCriterion("ORSLRemark >", value, "orslremark");
            return (Criteria) this;
        }

        public Criteria andOrslremarkGreaterThanOrEqualTo(String value) {
            addCriterion("ORSLRemark >=", value, "orslremark");
            return (Criteria) this;
        }

        public Criteria andOrslremarkLessThan(String value) {
            addCriterion("ORSLRemark <", value, "orslremark");
            return (Criteria) this;
        }

        public Criteria andOrslremarkLessThanOrEqualTo(String value) {
            addCriterion("ORSLRemark <=", value, "orslremark");
            return (Criteria) this;
        }

        public Criteria andOrslremarkLike(String value) {
            addCriterion("ORSLRemark like", value, "orslremark");
            return (Criteria) this;
        }

        public Criteria andOrslremarkNotLike(String value) {
            addCriterion("ORSLRemark not like", value, "orslremark");
            return (Criteria) this;
        }

        public Criteria andOrslremarkIn(List<String> values) {
            addCriterion("ORSLRemark in", values, "orslremark");
            return (Criteria) this;
        }

        public Criteria andOrslremarkNotIn(List<String> values) {
            addCriterion("ORSLRemark not in", values, "orslremark");
            return (Criteria) this;
        }

        public Criteria andOrslremarkBetween(String value1, String value2) {
            addCriterion("ORSLRemark between", value1, value2, "orslremark");
            return (Criteria) this;
        }

        public Criteria andOrslremarkNotBetween(String value1, String value2) {
            addCriterion("ORSLRemark not between", value1, value2, "orslremark");
            return (Criteria) this;
        }

        public Criteria andOrslordernoIsNull() {
            addCriterion("ORSLOrderNo is null");
            return (Criteria) this;
        }

        public Criteria andOrslordernoIsNotNull() {
            addCriterion("ORSLOrderNo is not null");
            return (Criteria) this;
        }

        public Criteria andOrslordernoEqualTo(String value) {
            addCriterion("ORSLOrderNo =", value, "orslorderno");
            return (Criteria) this;
        }

        public Criteria andOrslordernoNotEqualTo(String value) {
            addCriterion("ORSLOrderNo <>", value, "orslorderno");
            return (Criteria) this;
        }

        public Criteria andOrslordernoGreaterThan(String value) {
            addCriterion("ORSLOrderNo >", value, "orslorderno");
            return (Criteria) this;
        }

        public Criteria andOrslordernoGreaterThanOrEqualTo(String value) {
            addCriterion("ORSLOrderNo >=", value, "orslorderno");
            return (Criteria) this;
        }

        public Criteria andOrslordernoLessThan(String value) {
            addCriterion("ORSLOrderNo <", value, "orslorderno");
            return (Criteria) this;
        }

        public Criteria andOrslordernoLessThanOrEqualTo(String value) {
            addCriterion("ORSLOrderNo <=", value, "orslorderno");
            return (Criteria) this;
        }

        public Criteria andOrslordernoLike(String value) {
            addCriterion("ORSLOrderNo like", value, "orslorderno");
            return (Criteria) this;
        }

        public Criteria andOrslordernoNotLike(String value) {
            addCriterion("ORSLOrderNo not like", value, "orslorderno");
            return (Criteria) this;
        }

        public Criteria andOrslordernoIn(List<String> values) {
            addCriterion("ORSLOrderNo in", values, "orslorderno");
            return (Criteria) this;
        }

        public Criteria andOrslordernoNotIn(List<String> values) {
            addCriterion("ORSLOrderNo not in", values, "orslorderno");
            return (Criteria) this;
        }

        public Criteria andOrslordernoBetween(String value1, String value2) {
            addCriterion("ORSLOrderNo between", value1, value2, "orslorderno");
            return (Criteria) this;
        }

        public Criteria andOrslordernoNotBetween(String value1, String value2) {
            addCriterion("ORSLOrderNo not between", value1, value2, "orslorderno");
            return (Criteria) this;
        }

        public Criteria andOrslsupplieridIsNull() {
            addCriterion("ORSLSupplierID is null");
            return (Criteria) this;
        }

        public Criteria andOrslsupplieridIsNotNull() {
            addCriterion("ORSLSupplierID is not null");
            return (Criteria) this;
        }

        public Criteria andOrslsupplieridEqualTo(Integer value) {
            addCriterion("ORSLSupplierID =", value, "orslsupplierid");
            return (Criteria) this;
        }

        public Criteria andOrslsupplieridNotEqualTo(Integer value) {
            addCriterion("ORSLSupplierID <>", value, "orslsupplierid");
            return (Criteria) this;
        }

        public Criteria andOrslsupplieridGreaterThan(Integer value) {
            addCriterion("ORSLSupplierID >", value, "orslsupplierid");
            return (Criteria) this;
        }

        public Criteria andOrslsupplieridGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORSLSupplierID >=", value, "orslsupplierid");
            return (Criteria) this;
        }

        public Criteria andOrslsupplieridLessThan(Integer value) {
            addCriterion("ORSLSupplierID <", value, "orslsupplierid");
            return (Criteria) this;
        }

        public Criteria andOrslsupplieridLessThanOrEqualTo(Integer value) {
            addCriterion("ORSLSupplierID <=", value, "orslsupplierid");
            return (Criteria) this;
        }

        public Criteria andOrslsupplieridIn(List<Integer> values) {
            addCriterion("ORSLSupplierID in", values, "orslsupplierid");
            return (Criteria) this;
        }

        public Criteria andOrslsupplieridNotIn(List<Integer> values) {
            addCriterion("ORSLSupplierID not in", values, "orslsupplierid");
            return (Criteria) this;
        }

        public Criteria andOrslsupplieridBetween(Integer value1, Integer value2) {
            addCriterion("ORSLSupplierID between", value1, value2, "orslsupplierid");
            return (Criteria) this;
        }

        public Criteria andOrslsupplieridNotBetween(Integer value1, Integer value2) {
            addCriterion("ORSLSupplierID not between", value1, value2, "orslsupplierid");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierIsNull() {
            addCriterion("ORSLOrderNoOfSupplier is null");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierIsNotNull() {
            addCriterion("ORSLOrderNoOfSupplier is not null");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierEqualTo(String value) {
            addCriterion("ORSLOrderNoOfSupplier =", value, "orslordernoofsupplier");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierNotEqualTo(String value) {
            addCriterion("ORSLOrderNoOfSupplier <>", value, "orslordernoofsupplier");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierGreaterThan(String value) {
            addCriterion("ORSLOrderNoOfSupplier >", value, "orslordernoofsupplier");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierGreaterThanOrEqualTo(String value) {
            addCriterion("ORSLOrderNoOfSupplier >=", value, "orslordernoofsupplier");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierLessThan(String value) {
            addCriterion("ORSLOrderNoOfSupplier <", value, "orslordernoofsupplier");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierLessThanOrEqualTo(String value) {
            addCriterion("ORSLOrderNoOfSupplier <=", value, "orslordernoofsupplier");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierLike(String value) {
            addCriterion("ORSLOrderNoOfSupplier like", value, "orslordernoofsupplier");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierNotLike(String value) {
            addCriterion("ORSLOrderNoOfSupplier not like", value, "orslordernoofsupplier");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierIn(List<String> values) {
            addCriterion("ORSLOrderNoOfSupplier in", values, "orslordernoofsupplier");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierNotIn(List<String> values) {
            addCriterion("ORSLOrderNoOfSupplier not in", values, "orslordernoofsupplier");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierBetween(String value1, String value2) {
            addCriterion("ORSLOrderNoOfSupplier between", value1, value2, "orslordernoofsupplier");
            return (Criteria) this;
        }

        public Criteria andOrslordernoofsupplierNotBetween(String value1, String value2) {
            addCriterion("ORSLOrderNoOfSupplier not between", value1, value2, "orslordernoofsupplier");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 20 19:34:10 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderRequestSupplierLog
     *
     * @mbggenerated Wed Feb 20 19:34:10 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}