package com.adam.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderRoomExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    public OrderRoomExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrorderidIsNull() {
            addCriterion("OROrderID is null");
            return (Criteria) this;
        }

        public Criteria andOrorderidIsNotNull() {
            addCriterion("OROrderID is not null");
            return (Criteria) this;
        }

        public Criteria andOrorderidEqualTo(Integer value) {
            addCriterion("OROrderID =", value, "ororderid");
            return (Criteria) this;
        }

        public Criteria andOrorderidNotEqualTo(Integer value) {
            addCriterion("OROrderID <>", value, "ororderid");
            return (Criteria) this;
        }

        public Criteria andOrorderidGreaterThan(Integer value) {
            addCriterion("OROrderID >", value, "ororderid");
            return (Criteria) this;
        }

        public Criteria andOrorderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("OROrderID >=", value, "ororderid");
            return (Criteria) this;
        }

        public Criteria andOrorderidLessThan(Integer value) {
            addCriterion("OROrderID <", value, "ororderid");
            return (Criteria) this;
        }

        public Criteria andOrorderidLessThanOrEqualTo(Integer value) {
            addCriterion("OROrderID <=", value, "ororderid");
            return (Criteria) this;
        }

        public Criteria andOrorderidIn(List<Integer> values) {
            addCriterion("OROrderID in", values, "ororderid");
            return (Criteria) this;
        }

        public Criteria andOrorderidNotIn(List<Integer> values) {
            addCriterion("OROrderID not in", values, "ororderid");
            return (Criteria) this;
        }

        public Criteria andOrorderidBetween(Integer value1, Integer value2) {
            addCriterion("OROrderID between", value1, value2, "ororderid");
            return (Criteria) this;
        }

        public Criteria andOrorderidNotBetween(Integer value1, Integer value2) {
            addCriterion("OROrderID not between", value1, value2, "ororderid");
            return (Criteria) this;
        }

        public Criteria andOrordernoIsNull() {
            addCriterion("OROrderNo is null");
            return (Criteria) this;
        }

        public Criteria andOrordernoIsNotNull() {
            addCriterion("OROrderNo is not null");
            return (Criteria) this;
        }

        public Criteria andOrordernoEqualTo(String value) {
            addCriterion("OROrderNo =", value, "ororderno");
            return (Criteria) this;
        }

        public Criteria andOrordernoNotEqualTo(String value) {
            addCriterion("OROrderNo <>", value, "ororderno");
            return (Criteria) this;
        }

        public Criteria andOrordernoGreaterThan(String value) {
            addCriterion("OROrderNo >", value, "ororderno");
            return (Criteria) this;
        }

        public Criteria andOrordernoGreaterThanOrEqualTo(String value) {
            addCriterion("OROrderNo >=", value, "ororderno");
            return (Criteria) this;
        }

        public Criteria andOrordernoLessThan(String value) {
            addCriterion("OROrderNo <", value, "ororderno");
            return (Criteria) this;
        }

        public Criteria andOrordernoLessThanOrEqualTo(String value) {
            addCriterion("OROrderNo <=", value, "ororderno");
            return (Criteria) this;
        }

        public Criteria andOrordernoLike(String value) {
            addCriterion("OROrderNo like", value, "ororderno");
            return (Criteria) this;
        }

        public Criteria andOrordernoNotLike(String value) {
            addCriterion("OROrderNo not like", value, "ororderno");
            return (Criteria) this;
        }

        public Criteria andOrordernoIn(List<String> values) {
            addCriterion("OROrderNo in", values, "ororderno");
            return (Criteria) this;
        }

        public Criteria andOrordernoNotIn(List<String> values) {
            addCriterion("OROrderNo not in", values, "ororderno");
            return (Criteria) this;
        }

        public Criteria andOrordernoBetween(String value1, String value2) {
            addCriterion("OROrderNo between", value1, value2, "ororderno");
            return (Criteria) this;
        }

        public Criteria andOrordernoNotBetween(String value1, String value2) {
            addCriterion("OROrderNo not between", value1, value2, "ororderno");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoIsNull() {
            addCriterion("ORSupplierConfirmationNo is null");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoIsNotNull() {
            addCriterion("ORSupplierConfirmationNo is not null");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoEqualTo(String value) {
            addCriterion("ORSupplierConfirmationNo =", value, "orsupplierconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoNotEqualTo(String value) {
            addCriterion("ORSupplierConfirmationNo <>", value, "orsupplierconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoGreaterThan(String value) {
            addCriterion("ORSupplierConfirmationNo >", value, "orsupplierconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoGreaterThanOrEqualTo(String value) {
            addCriterion("ORSupplierConfirmationNo >=", value, "orsupplierconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoLessThan(String value) {
            addCriterion("ORSupplierConfirmationNo <", value, "orsupplierconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoLessThanOrEqualTo(String value) {
            addCriterion("ORSupplierConfirmationNo <=", value, "orsupplierconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoLike(String value) {
            addCriterion("ORSupplierConfirmationNo like", value, "orsupplierconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoNotLike(String value) {
            addCriterion("ORSupplierConfirmationNo not like", value, "orsupplierconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoIn(List<String> values) {
            addCriterion("ORSupplierConfirmationNo in", values, "orsupplierconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoNotIn(List<String> values) {
            addCriterion("ORSupplierConfirmationNo not in", values, "orsupplierconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoBetween(String value1, String value2) {
            addCriterion("ORSupplierConfirmationNo between", value1, value2, "orsupplierconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrsupplierconfirmationnoNotBetween(String value1, String value2) {
            addCriterion("ORSupplierConfirmationNo not between", value1, value2, "orsupplierconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoIsNull() {
            addCriterion("ORSupplierCancellationNo is null");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoIsNotNull() {
            addCriterion("ORSupplierCancellationNo is not null");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoEqualTo(String value) {
            addCriterion("ORSupplierCancellationNo =", value, "orsuppliercancellationno");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoNotEqualTo(String value) {
            addCriterion("ORSupplierCancellationNo <>", value, "orsuppliercancellationno");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoGreaterThan(String value) {
            addCriterion("ORSupplierCancellationNo >", value, "orsuppliercancellationno");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoGreaterThanOrEqualTo(String value) {
            addCriterion("ORSupplierCancellationNo >=", value, "orsuppliercancellationno");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoLessThan(String value) {
            addCriterion("ORSupplierCancellationNo <", value, "orsuppliercancellationno");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoLessThanOrEqualTo(String value) {
            addCriterion("ORSupplierCancellationNo <=", value, "orsuppliercancellationno");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoLike(String value) {
            addCriterion("ORSupplierCancellationNo like", value, "orsuppliercancellationno");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoNotLike(String value) {
            addCriterion("ORSupplierCancellationNo not like", value, "orsuppliercancellationno");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoIn(List<String> values) {
            addCriterion("ORSupplierCancellationNo in", values, "orsuppliercancellationno");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoNotIn(List<String> values) {
            addCriterion("ORSupplierCancellationNo not in", values, "orsuppliercancellationno");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoBetween(String value1, String value2) {
            addCriterion("ORSupplierCancellationNo between", value1, value2, "orsuppliercancellationno");
            return (Criteria) this;
        }

        public Criteria andOrsuppliercancellationnoNotBetween(String value1, String value2) {
            addCriterion("ORSupplierCancellationNo not between", value1, value2, "orsuppliercancellationno");
            return (Criteria) this;
        }

        public Criteria andOrcancellationreasonidIsNull() {
            addCriterion("ORCancellationReasonID is null");
            return (Criteria) this;
        }

        public Criteria andOrcancellationreasonidIsNotNull() {
            addCriterion("ORCancellationReasonID is not null");
            return (Criteria) this;
        }

        public Criteria andOrcancellationreasonidEqualTo(Integer value) {
            addCriterion("ORCancellationReasonID =", value, "orcancellationreasonid");
            return (Criteria) this;
        }

        public Criteria andOrcancellationreasonidNotEqualTo(Integer value) {
            addCriterion("ORCancellationReasonID <>", value, "orcancellationreasonid");
            return (Criteria) this;
        }

        public Criteria andOrcancellationreasonidGreaterThan(Integer value) {
            addCriterion("ORCancellationReasonID >", value, "orcancellationreasonid");
            return (Criteria) this;
        }

        public Criteria andOrcancellationreasonidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORCancellationReasonID >=", value, "orcancellationreasonid");
            return (Criteria) this;
        }

        public Criteria andOrcancellationreasonidLessThan(Integer value) {
            addCriterion("ORCancellationReasonID <", value, "orcancellationreasonid");
            return (Criteria) this;
        }

        public Criteria andOrcancellationreasonidLessThanOrEqualTo(Integer value) {
            addCriterion("ORCancellationReasonID <=", value, "orcancellationreasonid");
            return (Criteria) this;
        }

        public Criteria andOrcancellationreasonidIn(List<Integer> values) {
            addCriterion("ORCancellationReasonID in", values, "orcancellationreasonid");
            return (Criteria) this;
        }

        public Criteria andOrcancellationreasonidNotIn(List<Integer> values) {
            addCriterion("ORCancellationReasonID not in", values, "orcancellationreasonid");
            return (Criteria) this;
        }

        public Criteria andOrcancellationreasonidBetween(Integer value1, Integer value2) {
            addCriterion("ORCancellationReasonID between", value1, value2, "orcancellationreasonid");
            return (Criteria) this;
        }

        public Criteria andOrcancellationreasonidNotBetween(Integer value1, Integer value2) {
            addCriterion("ORCancellationReasonID not between", value1, value2, "orcancellationreasonid");
            return (Criteria) this;
        }

        public Criteria andOrcancellationdateIsNull() {
            addCriterion("ORCancellationDate is null");
            return (Criteria) this;
        }

        public Criteria andOrcancellationdateIsNotNull() {
            addCriterion("ORCancellationDate is not null");
            return (Criteria) this;
        }

        public Criteria andOrcancellationdateEqualTo(Date value) {
            addCriterion("ORCancellationDate =", value, "orcancellationdate");
            return (Criteria) this;
        }

        public Criteria andOrcancellationdateNotEqualTo(Date value) {
            addCriterion("ORCancellationDate <>", value, "orcancellationdate");
            return (Criteria) this;
        }

        public Criteria andOrcancellationdateGreaterThan(Date value) {
            addCriterion("ORCancellationDate >", value, "orcancellationdate");
            return (Criteria) this;
        }

        public Criteria andOrcancellationdateGreaterThanOrEqualTo(Date value) {
            addCriterion("ORCancellationDate >=", value, "orcancellationdate");
            return (Criteria) this;
        }

        public Criteria andOrcancellationdateLessThan(Date value) {
            addCriterion("ORCancellationDate <", value, "orcancellationdate");
            return (Criteria) this;
        }

        public Criteria andOrcancellationdateLessThanOrEqualTo(Date value) {
            addCriterion("ORCancellationDate <=", value, "orcancellationdate");
            return (Criteria) this;
        }

        public Criteria andOrcancellationdateIn(List<Date> values) {
            addCriterion("ORCancellationDate in", values, "orcancellationdate");
            return (Criteria) this;
        }

        public Criteria andOrcancellationdateNotIn(List<Date> values) {
            addCriterion("ORCancellationDate not in", values, "orcancellationdate");
            return (Criteria) this;
        }

        public Criteria andOrcancellationdateBetween(Date value1, Date value2) {
            addCriterion("ORCancellationDate between", value1, value2, "orcancellationdate");
            return (Criteria) this;
        }

        public Criteria andOrcancellationdateNotBetween(Date value1, Date value2) {
            addCriterion("ORCancellationDate not between", value1, value2, "orcancellationdate");
            return (Criteria) this;
        }

        public Criteria andOramountIsNull() {
            addCriterion("ORAmount is null");
            return (Criteria) this;
        }

        public Criteria andOramountIsNotNull() {
            addCriterion("ORAmount is not null");
            return (Criteria) this;
        }

        public Criteria andOramountEqualTo(BigDecimal value) {
            addCriterion("ORAmount =", value, "oramount");
            return (Criteria) this;
        }

        public Criteria andOramountNotEqualTo(BigDecimal value) {
            addCriterion("ORAmount <>", value, "oramount");
            return (Criteria) this;
        }

        public Criteria andOramountGreaterThan(BigDecimal value) {
            addCriterion("ORAmount >", value, "oramount");
            return (Criteria) this;
        }

        public Criteria andOramountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORAmount >=", value, "oramount");
            return (Criteria) this;
        }

        public Criteria andOramountLessThan(BigDecimal value) {
            addCriterion("ORAmount <", value, "oramount");
            return (Criteria) this;
        }

        public Criteria andOramountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORAmount <=", value, "oramount");
            return (Criteria) this;
        }

        public Criteria andOramountIn(List<BigDecimal> values) {
            addCriterion("ORAmount in", values, "oramount");
            return (Criteria) this;
        }

        public Criteria andOramountNotIn(List<BigDecimal> values) {
            addCriterion("ORAmount not in", values, "oramount");
            return (Criteria) this;
        }

        public Criteria andOramountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORAmount between", value1, value2, "oramount");
            return (Criteria) this;
        }

        public Criteria andOramountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORAmount not between", value1, value2, "oramount");
            return (Criteria) this;
        }

        public Criteria andOrcurrencyidIsNull() {
            addCriterion("ORCurrencyID is null");
            return (Criteria) this;
        }

        public Criteria andOrcurrencyidIsNotNull() {
            addCriterion("ORCurrencyID is not null");
            return (Criteria) this;
        }

        public Criteria andOrcurrencyidEqualTo(Integer value) {
            addCriterion("ORCurrencyID =", value, "orcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOrcurrencyidNotEqualTo(Integer value) {
            addCriterion("ORCurrencyID <>", value, "orcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOrcurrencyidGreaterThan(Integer value) {
            addCriterion("ORCurrencyID >", value, "orcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOrcurrencyidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORCurrencyID >=", value, "orcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOrcurrencyidLessThan(Integer value) {
            addCriterion("ORCurrencyID <", value, "orcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOrcurrencyidLessThanOrEqualTo(Integer value) {
            addCriterion("ORCurrencyID <=", value, "orcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOrcurrencyidIn(List<Integer> values) {
            addCriterion("ORCurrencyID in", values, "orcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOrcurrencyidNotIn(List<Integer> values) {
            addCriterion("ORCurrencyID not in", values, "orcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOrcurrencyidBetween(Integer value1, Integer value2) {
            addCriterion("ORCurrencyID between", value1, value2, "orcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOrcurrencyidNotBetween(Integer value1, Integer value2) {
            addCriterion("ORCurrencyID not between", value1, value2, "orcurrencyid");
            return (Criteria) this;
        }

        public Criteria andOrcomissionIsNull() {
            addCriterion("ORComission is null");
            return (Criteria) this;
        }

        public Criteria andOrcomissionIsNotNull() {
            addCriterion("ORComission is not null");
            return (Criteria) this;
        }

        public Criteria andOrcomissionEqualTo(BigDecimal value) {
            addCriterion("ORComission =", value, "orcomission");
            return (Criteria) this;
        }

        public Criteria andOrcomissionNotEqualTo(BigDecimal value) {
            addCriterion("ORComission <>", value, "orcomission");
            return (Criteria) this;
        }

        public Criteria andOrcomissionGreaterThan(BigDecimal value) {
            addCriterion("ORComission >", value, "orcomission");
            return (Criteria) this;
        }

        public Criteria andOrcomissionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORComission >=", value, "orcomission");
            return (Criteria) this;
        }

        public Criteria andOrcomissionLessThan(BigDecimal value) {
            addCriterion("ORComission <", value, "orcomission");
            return (Criteria) this;
        }

        public Criteria andOrcomissionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORComission <=", value, "orcomission");
            return (Criteria) this;
        }

        public Criteria andOrcomissionIn(List<BigDecimal> values) {
            addCriterion("ORComission in", values, "orcomission");
            return (Criteria) this;
        }

        public Criteria andOrcomissionNotIn(List<BigDecimal> values) {
            addCriterion("ORComission not in", values, "orcomission");
            return (Criteria) this;
        }

        public Criteria andOrcomissionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORComission between", value1, value2, "orcomission");
            return (Criteria) this;
        }

        public Criteria andOrcomissionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORComission not between", value1, value2, "orcomission");
            return (Criteria) this;
        }

        public Criteria andOrrefoundamountIsNull() {
            addCriterion("ORRefoundAmount is null");
            return (Criteria) this;
        }

        public Criteria andOrrefoundamountIsNotNull() {
            addCriterion("ORRefoundAmount is not null");
            return (Criteria) this;
        }

        public Criteria andOrrefoundamountEqualTo(BigDecimal value) {
            addCriterion("ORRefoundAmount =", value, "orrefoundamount");
            return (Criteria) this;
        }

        public Criteria andOrrefoundamountNotEqualTo(BigDecimal value) {
            addCriterion("ORRefoundAmount <>", value, "orrefoundamount");
            return (Criteria) this;
        }

        public Criteria andOrrefoundamountGreaterThan(BigDecimal value) {
            addCriterion("ORRefoundAmount >", value, "orrefoundamount");
            return (Criteria) this;
        }

        public Criteria andOrrefoundamountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORRefoundAmount >=", value, "orrefoundamount");
            return (Criteria) this;
        }

        public Criteria andOrrefoundamountLessThan(BigDecimal value) {
            addCriterion("ORRefoundAmount <", value, "orrefoundamount");
            return (Criteria) this;
        }

        public Criteria andOrrefoundamountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORRefoundAmount <=", value, "orrefoundamount");
            return (Criteria) this;
        }

        public Criteria andOrrefoundamountIn(List<BigDecimal> values) {
            addCriterion("ORRefoundAmount in", values, "orrefoundamount");
            return (Criteria) this;
        }

        public Criteria andOrrefoundamountNotIn(List<BigDecimal> values) {
            addCriterion("ORRefoundAmount not in", values, "orrefoundamount");
            return (Criteria) this;
        }

        public Criteria andOrrefoundamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORRefoundAmount between", value1, value2, "orrefoundamount");
            return (Criteria) this;
        }

        public Criteria andOrrefoundamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORRefoundAmount not between", value1, value2, "orrefoundamount");
            return (Criteria) this;
        }

        public Criteria andOrcancellationnightsIsNull() {
            addCriterion("ORCancellationNights is null");
            return (Criteria) this;
        }

        public Criteria andOrcancellationnightsIsNotNull() {
            addCriterion("ORCancellationNights is not null");
            return (Criteria) this;
        }

        public Criteria andOrcancellationnightsEqualTo(Integer value) {
            addCriterion("ORCancellationNights =", value, "orcancellationnights");
            return (Criteria) this;
        }

        public Criteria andOrcancellationnightsNotEqualTo(Integer value) {
            addCriterion("ORCancellationNights <>", value, "orcancellationnights");
            return (Criteria) this;
        }

        public Criteria andOrcancellationnightsGreaterThan(Integer value) {
            addCriterion("ORCancellationNights >", value, "orcancellationnights");
            return (Criteria) this;
        }

        public Criteria andOrcancellationnightsGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORCancellationNights >=", value, "orcancellationnights");
            return (Criteria) this;
        }

        public Criteria andOrcancellationnightsLessThan(Integer value) {
            addCriterion("ORCancellationNights <", value, "orcancellationnights");
            return (Criteria) this;
        }

        public Criteria andOrcancellationnightsLessThanOrEqualTo(Integer value) {
            addCriterion("ORCancellationNights <=", value, "orcancellationnights");
            return (Criteria) this;
        }

        public Criteria andOrcancellationnightsIn(List<Integer> values) {
            addCriterion("ORCancellationNights in", values, "orcancellationnights");
            return (Criteria) this;
        }

        public Criteria andOrcancellationnightsNotIn(List<Integer> values) {
            addCriterion("ORCancellationNights not in", values, "orcancellationnights");
            return (Criteria) this;
        }

        public Criteria andOrcancellationnightsBetween(Integer value1, Integer value2) {
            addCriterion("ORCancellationNights between", value1, value2, "orcancellationnights");
            return (Criteria) this;
        }

        public Criteria andOrcancellationnightsNotBetween(Integer value1, Integer value2) {
            addCriterion("ORCancellationNights not between", value1, value2, "orcancellationnights");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkIsNull() {
            addCriterion("ORGuestRemark is null");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkIsNotNull() {
            addCriterion("ORGuestRemark is not null");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkEqualTo(String value) {
            addCriterion("ORGuestRemark =", value, "orguestremark");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkNotEqualTo(String value) {
            addCriterion("ORGuestRemark <>", value, "orguestremark");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkGreaterThan(String value) {
            addCriterion("ORGuestRemark >", value, "orguestremark");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkGreaterThanOrEqualTo(String value) {
            addCriterion("ORGuestRemark >=", value, "orguestremark");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkLessThan(String value) {
            addCriterion("ORGuestRemark <", value, "orguestremark");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkLessThanOrEqualTo(String value) {
            addCriterion("ORGuestRemark <=", value, "orguestremark");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkLike(String value) {
            addCriterion("ORGuestRemark like", value, "orguestremark");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkNotLike(String value) {
            addCriterion("ORGuestRemark not like", value, "orguestremark");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkIn(List<String> values) {
            addCriterion("ORGuestRemark in", values, "orguestremark");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkNotIn(List<String> values) {
            addCriterion("ORGuestRemark not in", values, "orguestremark");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkBetween(String value1, String value2) {
            addCriterion("ORGuestRemark between", value1, value2, "orguestremark");
            return (Criteria) this;
        }

        public Criteria andOrguestremarkNotBetween(String value1, String value2) {
            addCriterion("ORGuestRemark not between", value1, value2, "orguestremark");
            return (Criteria) this;
        }

        public Criteria andOrroomnoIsNull() {
            addCriterion("ORRoomNo is null");
            return (Criteria) this;
        }

        public Criteria andOrroomnoIsNotNull() {
            addCriterion("ORRoomNo is not null");
            return (Criteria) this;
        }

        public Criteria andOrroomnoEqualTo(String value) {
            addCriterion("ORRoomNo =", value, "orroomno");
            return (Criteria) this;
        }

        public Criteria andOrroomnoNotEqualTo(String value) {
            addCriterion("ORRoomNo <>", value, "orroomno");
            return (Criteria) this;
        }

        public Criteria andOrroomnoGreaterThan(String value) {
            addCriterion("ORRoomNo >", value, "orroomno");
            return (Criteria) this;
        }

        public Criteria andOrroomnoGreaterThanOrEqualTo(String value) {
            addCriterion("ORRoomNo >=", value, "orroomno");
            return (Criteria) this;
        }

        public Criteria andOrroomnoLessThan(String value) {
            addCriterion("ORRoomNo <", value, "orroomno");
            return (Criteria) this;
        }

        public Criteria andOrroomnoLessThanOrEqualTo(String value) {
            addCriterion("ORRoomNo <=", value, "orroomno");
            return (Criteria) this;
        }

        public Criteria andOrroomnoLike(String value) {
            addCriterion("ORRoomNo like", value, "orroomno");
            return (Criteria) this;
        }

        public Criteria andOrroomnoNotLike(String value) {
            addCriterion("ORRoomNo not like", value, "orroomno");
            return (Criteria) this;
        }

        public Criteria andOrroomnoIn(List<String> values) {
            addCriterion("ORRoomNo in", values, "orroomno");
            return (Criteria) this;
        }

        public Criteria andOrroomnoNotIn(List<String> values) {
            addCriterion("ORRoomNo not in", values, "orroomno");
            return (Criteria) this;
        }

        public Criteria andOrroomnoBetween(String value1, String value2) {
            addCriterion("ORRoomNo between", value1, value2, "orroomno");
            return (Criteria) this;
        }

        public Criteria andOrroomnoNotBetween(String value1, String value2) {
            addCriterion("ORRoomNo not between", value1, value2, "orroomno");
            return (Criteria) this;
        }

        public Criteria andOrnumberofadultsIsNull() {
            addCriterion("ORNumberOfAdults is null");
            return (Criteria) this;
        }

        public Criteria andOrnumberofadultsIsNotNull() {
            addCriterion("ORNumberOfAdults is not null");
            return (Criteria) this;
        }

        public Criteria andOrnumberofadultsEqualTo(Integer value) {
            addCriterion("ORNumberOfAdults =", value, "ornumberofadults");
            return (Criteria) this;
        }

        public Criteria andOrnumberofadultsNotEqualTo(Integer value) {
            addCriterion("ORNumberOfAdults <>", value, "ornumberofadults");
            return (Criteria) this;
        }

        public Criteria andOrnumberofadultsGreaterThan(Integer value) {
            addCriterion("ORNumberOfAdults >", value, "ornumberofadults");
            return (Criteria) this;
        }

        public Criteria andOrnumberofadultsGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORNumberOfAdults >=", value, "ornumberofadults");
            return (Criteria) this;
        }

        public Criteria andOrnumberofadultsLessThan(Integer value) {
            addCriterion("ORNumberOfAdults <", value, "ornumberofadults");
            return (Criteria) this;
        }

        public Criteria andOrnumberofadultsLessThanOrEqualTo(Integer value) {
            addCriterion("ORNumberOfAdults <=", value, "ornumberofadults");
            return (Criteria) this;
        }

        public Criteria andOrnumberofadultsIn(List<Integer> values) {
            addCriterion("ORNumberOfAdults in", values, "ornumberofadults");
            return (Criteria) this;
        }

        public Criteria andOrnumberofadultsNotIn(List<Integer> values) {
            addCriterion("ORNumberOfAdults not in", values, "ornumberofadults");
            return (Criteria) this;
        }

        public Criteria andOrnumberofadultsBetween(Integer value1, Integer value2) {
            addCriterion("ORNumberOfAdults between", value1, value2, "ornumberofadults");
            return (Criteria) this;
        }

        public Criteria andOrnumberofadultsNotBetween(Integer value1, Integer value2) {
            addCriterion("ORNumberOfAdults not between", value1, value2, "ornumberofadults");
            return (Criteria) this;
        }

        public Criteria andOrnumberofchidrenIsNull() {
            addCriterion("ORNumberOfChidren is null");
            return (Criteria) this;
        }

        public Criteria andOrnumberofchidrenIsNotNull() {
            addCriterion("ORNumberOfChidren is not null");
            return (Criteria) this;
        }

        public Criteria andOrnumberofchidrenEqualTo(Integer value) {
            addCriterion("ORNumberOfChidren =", value, "ornumberofchidren");
            return (Criteria) this;
        }

        public Criteria andOrnumberofchidrenNotEqualTo(Integer value) {
            addCriterion("ORNumberOfChidren <>", value, "ornumberofchidren");
            return (Criteria) this;
        }

        public Criteria andOrnumberofchidrenGreaterThan(Integer value) {
            addCriterion("ORNumberOfChidren >", value, "ornumberofchidren");
            return (Criteria) this;
        }

        public Criteria andOrnumberofchidrenGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORNumberOfChidren >=", value, "ornumberofchidren");
            return (Criteria) this;
        }

        public Criteria andOrnumberofchidrenLessThan(Integer value) {
            addCriterion("ORNumberOfChidren <", value, "ornumberofchidren");
            return (Criteria) this;
        }

        public Criteria andOrnumberofchidrenLessThanOrEqualTo(Integer value) {
            addCriterion("ORNumberOfChidren <=", value, "ornumberofchidren");
            return (Criteria) this;
        }

        public Criteria andOrnumberofchidrenIn(List<Integer> values) {
            addCriterion("ORNumberOfChidren in", values, "ornumberofchidren");
            return (Criteria) this;
        }

        public Criteria andOrnumberofchidrenNotIn(List<Integer> values) {
            addCriterion("ORNumberOfChidren not in", values, "ornumberofchidren");
            return (Criteria) this;
        }

        public Criteria andOrnumberofchidrenBetween(Integer value1, Integer value2) {
            addCriterion("ORNumberOfChidren between", value1, value2, "ornumberofchidren");
            return (Criteria) this;
        }

        public Criteria andOrnumberofchidrenNotBetween(Integer value1, Integer value2) {
            addCriterion("ORNumberOfChidren not between", value1, value2, "ornumberofchidren");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceIsNull() {
            addCriterion("ORSmokingPreference is null");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceIsNotNull() {
            addCriterion("ORSmokingPreference is not null");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceEqualTo(String value) {
            addCriterion("ORSmokingPreference =", value, "orsmokingpreference");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceNotEqualTo(String value) {
            addCriterion("ORSmokingPreference <>", value, "orsmokingpreference");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceGreaterThan(String value) {
            addCriterion("ORSmokingPreference >", value, "orsmokingpreference");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceGreaterThanOrEqualTo(String value) {
            addCriterion("ORSmokingPreference >=", value, "orsmokingpreference");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceLessThan(String value) {
            addCriterion("ORSmokingPreference <", value, "orsmokingpreference");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceLessThanOrEqualTo(String value) {
            addCriterion("ORSmokingPreference <=", value, "orsmokingpreference");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceLike(String value) {
            addCriterion("ORSmokingPreference like", value, "orsmokingpreference");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceNotLike(String value) {
            addCriterion("ORSmokingPreference not like", value, "orsmokingpreference");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceIn(List<String> values) {
            addCriterion("ORSmokingPreference in", values, "orsmokingpreference");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceNotIn(List<String> values) {
            addCriterion("ORSmokingPreference not in", values, "orsmokingpreference");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceBetween(String value1, String value2) {
            addCriterion("ORSmokingPreference between", value1, value2, "orsmokingpreference");
            return (Criteria) this;
        }

        public Criteria andOrsmokingpreferenceNotBetween(String value1, String value2) {
            addCriterion("ORSmokingPreference not between", value1, value2, "orsmokingpreference");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameIsNull() {
            addCriterion("ORGuestFirstName is null");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameIsNotNull() {
            addCriterion("ORGuestFirstName is not null");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameEqualTo(String value) {
            addCriterion("ORGuestFirstName =", value, "orguestfirstname");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameNotEqualTo(String value) {
            addCriterion("ORGuestFirstName <>", value, "orguestfirstname");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameGreaterThan(String value) {
            addCriterion("ORGuestFirstName >", value, "orguestfirstname");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameGreaterThanOrEqualTo(String value) {
            addCriterion("ORGuestFirstName >=", value, "orguestfirstname");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameLessThan(String value) {
            addCriterion("ORGuestFirstName <", value, "orguestfirstname");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameLessThanOrEqualTo(String value) {
            addCriterion("ORGuestFirstName <=", value, "orguestfirstname");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameLike(String value) {
            addCriterion("ORGuestFirstName like", value, "orguestfirstname");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameNotLike(String value) {
            addCriterion("ORGuestFirstName not like", value, "orguestfirstname");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameIn(List<String> values) {
            addCriterion("ORGuestFirstName in", values, "orguestfirstname");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameNotIn(List<String> values) {
            addCriterion("ORGuestFirstName not in", values, "orguestfirstname");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameBetween(String value1, String value2) {
            addCriterion("ORGuestFirstName between", value1, value2, "orguestfirstname");
            return (Criteria) this;
        }

        public Criteria andOrguestfirstnameNotBetween(String value1, String value2) {
            addCriterion("ORGuestFirstName not between", value1, value2, "orguestfirstname");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameIsNull() {
            addCriterion("ORGuestLastName is null");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameIsNotNull() {
            addCriterion("ORGuestLastName is not null");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameEqualTo(String value) {
            addCriterion("ORGuestLastName =", value, "orguestlastname");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameNotEqualTo(String value) {
            addCriterion("ORGuestLastName <>", value, "orguestlastname");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameGreaterThan(String value) {
            addCriterion("ORGuestLastName >", value, "orguestlastname");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameGreaterThanOrEqualTo(String value) {
            addCriterion("ORGuestLastName >=", value, "orguestlastname");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameLessThan(String value) {
            addCriterion("ORGuestLastName <", value, "orguestlastname");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameLessThanOrEqualTo(String value) {
            addCriterion("ORGuestLastName <=", value, "orguestlastname");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameLike(String value) {
            addCriterion("ORGuestLastName like", value, "orguestlastname");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameNotLike(String value) {
            addCriterion("ORGuestLastName not like", value, "orguestlastname");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameIn(List<String> values) {
            addCriterion("ORGuestLastName in", values, "orguestlastname");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameNotIn(List<String> values) {
            addCriterion("ORGuestLastName not in", values, "orguestlastname");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameBetween(String value1, String value2) {
            addCriterion("ORGuestLastName between", value1, value2, "orguestlastname");
            return (Criteria) this;
        }

        public Criteria andOrguestlastnameNotBetween(String value1, String value2) {
            addCriterion("ORGuestLastName not between", value1, value2, "orguestlastname");
            return (Criteria) this;
        }

        public Criteria andOrchildagesIsNull() {
            addCriterion("ORChildAges is null");
            return (Criteria) this;
        }

        public Criteria andOrchildagesIsNotNull() {
            addCriterion("ORChildAges is not null");
            return (Criteria) this;
        }

        public Criteria andOrchildagesEqualTo(String value) {
            addCriterion("ORChildAges =", value, "orchildages");
            return (Criteria) this;
        }

        public Criteria andOrchildagesNotEqualTo(String value) {
            addCriterion("ORChildAges <>", value, "orchildages");
            return (Criteria) this;
        }

        public Criteria andOrchildagesGreaterThan(String value) {
            addCriterion("ORChildAges >", value, "orchildages");
            return (Criteria) this;
        }

        public Criteria andOrchildagesGreaterThanOrEqualTo(String value) {
            addCriterion("ORChildAges >=", value, "orchildages");
            return (Criteria) this;
        }

        public Criteria andOrchildagesLessThan(String value) {
            addCriterion("ORChildAges <", value, "orchildages");
            return (Criteria) this;
        }

        public Criteria andOrchildagesLessThanOrEqualTo(String value) {
            addCriterion("ORChildAges <=", value, "orchildages");
            return (Criteria) this;
        }

        public Criteria andOrchildagesLike(String value) {
            addCriterion("ORChildAges like", value, "orchildages");
            return (Criteria) this;
        }

        public Criteria andOrchildagesNotLike(String value) {
            addCriterion("ORChildAges not like", value, "orchildages");
            return (Criteria) this;
        }

        public Criteria andOrchildagesIn(List<String> values) {
            addCriterion("ORChildAges in", values, "orchildages");
            return (Criteria) this;
        }

        public Criteria andOrchildagesNotIn(List<String> values) {
            addCriterion("ORChildAges not in", values, "orchildages");
            return (Criteria) this;
        }

        public Criteria andOrchildagesBetween(String value1, String value2) {
            addCriterion("ORChildAges between", value1, value2, "orchildages");
            return (Criteria) this;
        }

        public Criteria andOrchildagesNotBetween(String value1, String value2) {
            addCriterion("ORChildAges not between", value1, value2, "orchildages");
            return (Criteria) this;
        }

        public Criteria andOrbedtypeidIsNull() {
            addCriterion("ORBedTypeID is null");
            return (Criteria) this;
        }

        public Criteria andOrbedtypeidIsNotNull() {
            addCriterion("ORBedTypeID is not null");
            return (Criteria) this;
        }

        public Criteria andOrbedtypeidEqualTo(Integer value) {
            addCriterion("ORBedTypeID =", value, "orbedtypeid");
            return (Criteria) this;
        }

        public Criteria andOrbedtypeidNotEqualTo(Integer value) {
            addCriterion("ORBedTypeID <>", value, "orbedtypeid");
            return (Criteria) this;
        }

        public Criteria andOrbedtypeidGreaterThan(Integer value) {
            addCriterion("ORBedTypeID >", value, "orbedtypeid");
            return (Criteria) this;
        }

        public Criteria andOrbedtypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORBedTypeID >=", value, "orbedtypeid");
            return (Criteria) this;
        }

        public Criteria andOrbedtypeidLessThan(Integer value) {
            addCriterion("ORBedTypeID <", value, "orbedtypeid");
            return (Criteria) this;
        }

        public Criteria andOrbedtypeidLessThanOrEqualTo(Integer value) {
            addCriterion("ORBedTypeID <=", value, "orbedtypeid");
            return (Criteria) this;
        }

        public Criteria andOrbedtypeidIn(List<Integer> values) {
            addCriterion("ORBedTypeID in", values, "orbedtypeid");
            return (Criteria) this;
        }

        public Criteria andOrbedtypeidNotIn(List<Integer> values) {
            addCriterion("ORBedTypeID not in", values, "orbedtypeid");
            return (Criteria) this;
        }

        public Criteria andOrbedtypeidBetween(Integer value1, Integer value2) {
            addCriterion("ORBedTypeID between", value1, value2, "orbedtypeid");
            return (Criteria) this;
        }

        public Criteria andOrbedtypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("ORBedTypeID not between", value1, value2, "orbedtypeid");
            return (Criteria) this;
        }

        public Criteria andOrnumberofbedsIsNull() {
            addCriterion("ORNumberOfBeds is null");
            return (Criteria) this;
        }

        public Criteria andOrnumberofbedsIsNotNull() {
            addCriterion("ORNumberOfBeds is not null");
            return (Criteria) this;
        }

        public Criteria andOrnumberofbedsEqualTo(Integer value) {
            addCriterion("ORNumberOfBeds =", value, "ornumberofbeds");
            return (Criteria) this;
        }

        public Criteria andOrnumberofbedsNotEqualTo(Integer value) {
            addCriterion("ORNumberOfBeds <>", value, "ornumberofbeds");
            return (Criteria) this;
        }

        public Criteria andOrnumberofbedsGreaterThan(Integer value) {
            addCriterion("ORNumberOfBeds >", value, "ornumberofbeds");
            return (Criteria) this;
        }

        public Criteria andOrnumberofbedsGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORNumberOfBeds >=", value, "ornumberofbeds");
            return (Criteria) this;
        }

        public Criteria andOrnumberofbedsLessThan(Integer value) {
            addCriterion("ORNumberOfBeds <", value, "ornumberofbeds");
            return (Criteria) this;
        }

        public Criteria andOrnumberofbedsLessThanOrEqualTo(Integer value) {
            addCriterion("ORNumberOfBeds <=", value, "ornumberofbeds");
            return (Criteria) this;
        }

        public Criteria andOrnumberofbedsIn(List<Integer> values) {
            addCriterion("ORNumberOfBeds in", values, "ornumberofbeds");
            return (Criteria) this;
        }

        public Criteria andOrnumberofbedsNotIn(List<Integer> values) {
            addCriterion("ORNumberOfBeds not in", values, "ornumberofbeds");
            return (Criteria) this;
        }

        public Criteria andOrnumberofbedsBetween(Integer value1, Integer value2) {
            addCriterion("ORNumberOfBeds between", value1, value2, "ornumberofbeds");
            return (Criteria) this;
        }

        public Criteria andOrnumberofbedsNotBetween(Integer value1, Integer value2) {
            addCriterion("ORNumberOfBeds not between", value1, value2, "ornumberofbeds");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsIsNull() {
            addCriterion("ORNightlyAmounts is null");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsIsNotNull() {
            addCriterion("ORNightlyAmounts is not null");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsEqualTo(String value) {
            addCriterion("ORNightlyAmounts =", value, "ornightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsNotEqualTo(String value) {
            addCriterion("ORNightlyAmounts <>", value, "ornightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsGreaterThan(String value) {
            addCriterion("ORNightlyAmounts >", value, "ornightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsGreaterThanOrEqualTo(String value) {
            addCriterion("ORNightlyAmounts >=", value, "ornightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsLessThan(String value) {
            addCriterion("ORNightlyAmounts <", value, "ornightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsLessThanOrEqualTo(String value) {
            addCriterion("ORNightlyAmounts <=", value, "ornightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsLike(String value) {
            addCriterion("ORNightlyAmounts like", value, "ornightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsNotLike(String value) {
            addCriterion("ORNightlyAmounts not like", value, "ornightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsIn(List<String> values) {
            addCriterion("ORNightlyAmounts in", values, "ornightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsNotIn(List<String> values) {
            addCriterion("ORNightlyAmounts not in", values, "ornightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsBetween(String value1, String value2) {
            addCriterion("ORNightlyAmounts between", value1, value2, "ornightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrnightlyamountsNotBetween(String value1, String value2) {
            addCriterion("ORNightlyAmounts not between", value1, value2, "ornightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrratekeyIsNull() {
            addCriterion("ORRateKey is null");
            return (Criteria) this;
        }

        public Criteria andOrratekeyIsNotNull() {
            addCriterion("ORRateKey is not null");
            return (Criteria) this;
        }

        public Criteria andOrratekeyEqualTo(String value) {
            addCriterion("ORRateKey =", value, "orratekey");
            return (Criteria) this;
        }

        public Criteria andOrratekeyNotEqualTo(String value) {
            addCriterion("ORRateKey <>", value, "orratekey");
            return (Criteria) this;
        }

        public Criteria andOrratekeyGreaterThan(String value) {
            addCriterion("ORRateKey >", value, "orratekey");
            return (Criteria) this;
        }

        public Criteria andOrratekeyGreaterThanOrEqualTo(String value) {
            addCriterion("ORRateKey >=", value, "orratekey");
            return (Criteria) this;
        }

        public Criteria andOrratekeyLessThan(String value) {
            addCriterion("ORRateKey <", value, "orratekey");
            return (Criteria) this;
        }

        public Criteria andOrratekeyLessThanOrEqualTo(String value) {
            addCriterion("ORRateKey <=", value, "orratekey");
            return (Criteria) this;
        }

        public Criteria andOrratekeyLike(String value) {
            addCriterion("ORRateKey like", value, "orratekey");
            return (Criteria) this;
        }

        public Criteria andOrratekeyNotLike(String value) {
            addCriterion("ORRateKey not like", value, "orratekey");
            return (Criteria) this;
        }

        public Criteria andOrratekeyIn(List<String> values) {
            addCriterion("ORRateKey in", values, "orratekey");
            return (Criteria) this;
        }

        public Criteria andOrratekeyNotIn(List<String> values) {
            addCriterion("ORRateKey not in", values, "orratekey");
            return (Criteria) this;
        }

        public Criteria andOrratekeyBetween(String value1, String value2) {
            addCriterion("ORRateKey between", value1, value2, "orratekey");
            return (Criteria) this;
        }

        public Criteria andOrratekeyNotBetween(String value1, String value2) {
            addCriterion("ORRateKey not between", value1, value2, "orratekey");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameIsNull() {
            addCriterion("ORBedTypeName is null");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameIsNotNull() {
            addCriterion("ORBedTypeName is not null");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameEqualTo(String value) {
            addCriterion("ORBedTypeName =", value, "orbedtypename");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameNotEqualTo(String value) {
            addCriterion("ORBedTypeName <>", value, "orbedtypename");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameGreaterThan(String value) {
            addCriterion("ORBedTypeName >", value, "orbedtypename");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameGreaterThanOrEqualTo(String value) {
            addCriterion("ORBedTypeName >=", value, "orbedtypename");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameLessThan(String value) {
            addCriterion("ORBedTypeName <", value, "orbedtypename");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameLessThanOrEqualTo(String value) {
            addCriterion("ORBedTypeName <=", value, "orbedtypename");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameLike(String value) {
            addCriterion("ORBedTypeName like", value, "orbedtypename");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameNotLike(String value) {
            addCriterion("ORBedTypeName not like", value, "orbedtypename");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameIn(List<String> values) {
            addCriterion("ORBedTypeName in", values, "orbedtypename");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameNotIn(List<String> values) {
            addCriterion("ORBedTypeName not in", values, "orbedtypename");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameBetween(String value1, String value2) {
            addCriterion("ORBedTypeName between", value1, value2, "orbedtypename");
            return (Criteria) this;
        }

        public Criteria andOrbedtypenameNotBetween(String value1, String value2) {
            addCriterion("ORBedTypeName not between", value1, value2, "orbedtypename");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityIsNull() {
            addCriterion("ORGuestNationality is null");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityIsNotNull() {
            addCriterion("ORGuestNationality is not null");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityEqualTo(String value) {
            addCriterion("ORGuestNationality =", value, "orguestnationality");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityNotEqualTo(String value) {
            addCriterion("ORGuestNationality <>", value, "orguestnationality");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityGreaterThan(String value) {
            addCriterion("ORGuestNationality >", value, "orguestnationality");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityGreaterThanOrEqualTo(String value) {
            addCriterion("ORGuestNationality >=", value, "orguestnationality");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityLessThan(String value) {
            addCriterion("ORGuestNationality <", value, "orguestnationality");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityLessThanOrEqualTo(String value) {
            addCriterion("ORGuestNationality <=", value, "orguestnationality");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityLike(String value) {
            addCriterion("ORGuestNationality like", value, "orguestnationality");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityNotLike(String value) {
            addCriterion("ORGuestNationality not like", value, "orguestnationality");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityIn(List<String> values) {
            addCriterion("ORGuestNationality in", values, "orguestnationality");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityNotIn(List<String> values) {
            addCriterion("ORGuestNationality not in", values, "orguestnationality");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityBetween(String value1, String value2) {
            addCriterion("ORGuestNationality between", value1, value2, "orguestnationality");
            return (Criteria) this;
        }

        public Criteria andOrguestnationalityNotBetween(String value1, String value2) {
            addCriterion("ORGuestNationality not between", value1, value2, "orguestnationality");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesIsNull() {
            addCriterion("ORGuestOtherNames is null");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesIsNotNull() {
            addCriterion("ORGuestOtherNames is not null");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesEqualTo(String value) {
            addCriterion("ORGuestOtherNames =", value, "orguestothernames");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesNotEqualTo(String value) {
            addCriterion("ORGuestOtherNames <>", value, "orguestothernames");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesGreaterThan(String value) {
            addCriterion("ORGuestOtherNames >", value, "orguestothernames");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesGreaterThanOrEqualTo(String value) {
            addCriterion("ORGuestOtherNames >=", value, "orguestothernames");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesLessThan(String value) {
            addCriterion("ORGuestOtherNames <", value, "orguestothernames");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesLessThanOrEqualTo(String value) {
            addCriterion("ORGuestOtherNames <=", value, "orguestothernames");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesLike(String value) {
            addCriterion("ORGuestOtherNames like", value, "orguestothernames");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesNotLike(String value) {
            addCriterion("ORGuestOtherNames not like", value, "orguestothernames");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesIn(List<String> values) {
            addCriterion("ORGuestOtherNames in", values, "orguestothernames");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesNotIn(List<String> values) {
            addCriterion("ORGuestOtherNames not in", values, "orguestothernames");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesBetween(String value1, String value2) {
            addCriterion("ORGuestOtherNames between", value1, value2, "orguestothernames");
            return (Criteria) this;
        }

        public Criteria andOrguestothernamesNotBetween(String value1, String value2) {
            addCriterion("ORGuestOtherNames not between", value1, value2, "orguestothernames");
            return (Criteria) this;
        }

        public Criteria andOrconfirmationnoupdateIsNull() {
            addCriterion("ORConfirmationNoUpdate is null");
            return (Criteria) this;
        }

        public Criteria andOrconfirmationnoupdateIsNotNull() {
            addCriterion("ORConfirmationNoUpdate is not null");
            return (Criteria) this;
        }

        public Criteria andOrconfirmationnoupdateEqualTo(Boolean value) {
            addCriterion("ORConfirmationNoUpdate =", value, "orconfirmationnoupdate");
            return (Criteria) this;
        }

        public Criteria andOrconfirmationnoupdateNotEqualTo(Boolean value) {
            addCriterion("ORConfirmationNoUpdate <>", value, "orconfirmationnoupdate");
            return (Criteria) this;
        }

        public Criteria andOrconfirmationnoupdateGreaterThan(Boolean value) {
            addCriterion("ORConfirmationNoUpdate >", value, "orconfirmationnoupdate");
            return (Criteria) this;
        }

        public Criteria andOrconfirmationnoupdateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ORConfirmationNoUpdate >=", value, "orconfirmationnoupdate");
            return (Criteria) this;
        }

        public Criteria andOrconfirmationnoupdateLessThan(Boolean value) {
            addCriterion("ORConfirmationNoUpdate <", value, "orconfirmationnoupdate");
            return (Criteria) this;
        }

        public Criteria andOrconfirmationnoupdateLessThanOrEqualTo(Boolean value) {
            addCriterion("ORConfirmationNoUpdate <=", value, "orconfirmationnoupdate");
            return (Criteria) this;
        }

        public Criteria andOrconfirmationnoupdateIn(List<Boolean> values) {
            addCriterion("ORConfirmationNoUpdate in", values, "orconfirmationnoupdate");
            return (Criteria) this;
        }

        public Criteria andOrconfirmationnoupdateNotIn(List<Boolean> values) {
            addCriterion("ORConfirmationNoUpdate not in", values, "orconfirmationnoupdate");
            return (Criteria) this;
        }

        public Criteria andOrconfirmationnoupdateBetween(Boolean value1, Boolean value2) {
            addCriterion("ORConfirmationNoUpdate between", value1, value2, "orconfirmationnoupdate");
            return (Criteria) this;
        }

        public Criteria andOrconfirmationnoupdateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ORConfirmationNoUpdate not between", value1, value2, "orconfirmationnoupdate");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsIsNull() {
            addCriterion("ORSupplierNightlyAmounts is null");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsIsNotNull() {
            addCriterion("ORSupplierNightlyAmounts is not null");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsEqualTo(String value) {
            addCriterion("ORSupplierNightlyAmounts =", value, "orsuppliernightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsNotEqualTo(String value) {
            addCriterion("ORSupplierNightlyAmounts <>", value, "orsuppliernightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsGreaterThan(String value) {
            addCriterion("ORSupplierNightlyAmounts >", value, "orsuppliernightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsGreaterThanOrEqualTo(String value) {
            addCriterion("ORSupplierNightlyAmounts >=", value, "orsuppliernightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsLessThan(String value) {
            addCriterion("ORSupplierNightlyAmounts <", value, "orsuppliernightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsLessThanOrEqualTo(String value) {
            addCriterion("ORSupplierNightlyAmounts <=", value, "orsuppliernightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsLike(String value) {
            addCriterion("ORSupplierNightlyAmounts like", value, "orsuppliernightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsNotLike(String value) {
            addCriterion("ORSupplierNightlyAmounts not like", value, "orsuppliernightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsIn(List<String> values) {
            addCriterion("ORSupplierNightlyAmounts in", values, "orsuppliernightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsNotIn(List<String> values) {
            addCriterion("ORSupplierNightlyAmounts not in", values, "orsuppliernightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsBetween(String value1, String value2) {
            addCriterion("ORSupplierNightlyAmounts between", value1, value2, "orsuppliernightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyamountsNotBetween(String value1, String value2) {
            addCriterion("ORSupplierNightlyAmounts not between", value1, value2, "orsuppliernightlyamounts");
            return (Criteria) this;
        }

        public Criteria andOrsuppliertotaltaxIsNull() {
            addCriterion("ORSupplierTotalTax is null");
            return (Criteria) this;
        }

        public Criteria andOrsuppliertotaltaxIsNotNull() {
            addCriterion("ORSupplierTotalTax is not null");
            return (Criteria) this;
        }

        public Criteria andOrsuppliertotaltaxEqualTo(BigDecimal value) {
            addCriterion("ORSupplierTotalTax =", value, "orsuppliertotaltax");
            return (Criteria) this;
        }

        public Criteria andOrsuppliertotaltaxNotEqualTo(BigDecimal value) {
            addCriterion("ORSupplierTotalTax <>", value, "orsuppliertotaltax");
            return (Criteria) this;
        }

        public Criteria andOrsuppliertotaltaxGreaterThan(BigDecimal value) {
            addCriterion("ORSupplierTotalTax >", value, "orsuppliertotaltax");
            return (Criteria) this;
        }

        public Criteria andOrsuppliertotaltaxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORSupplierTotalTax >=", value, "orsuppliertotaltax");
            return (Criteria) this;
        }

        public Criteria andOrsuppliertotaltaxLessThan(BigDecimal value) {
            addCriterion("ORSupplierTotalTax <", value, "orsuppliertotaltax");
            return (Criteria) this;
        }

        public Criteria andOrsuppliertotaltaxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORSupplierTotalTax <=", value, "orsuppliertotaltax");
            return (Criteria) this;
        }

        public Criteria andOrsuppliertotaltaxIn(List<BigDecimal> values) {
            addCriterion("ORSupplierTotalTax in", values, "orsuppliertotaltax");
            return (Criteria) this;
        }

        public Criteria andOrsuppliertotaltaxNotIn(List<BigDecimal> values) {
            addCriterion("ORSupplierTotalTax not in", values, "orsuppliertotaltax");
            return (Criteria) this;
        }

        public Criteria andOrsuppliertotaltaxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORSupplierTotalTax between", value1, value2, "orsuppliertotaltax");
            return (Criteria) this;
        }

        public Criteria andOrsuppliertotaltaxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORSupplierTotalTax not between", value1, value2, "orsuppliertotaltax");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceIsNull() {
            addCriterion("ORSupplierNightlyRoomPrice is null");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceIsNotNull() {
            addCriterion("ORSupplierNightlyRoomPrice is not null");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceEqualTo(String value) {
            addCriterion("ORSupplierNightlyRoomPrice =", value, "orsuppliernightlyroomprice");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceNotEqualTo(String value) {
            addCriterion("ORSupplierNightlyRoomPrice <>", value, "orsuppliernightlyroomprice");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceGreaterThan(String value) {
            addCriterion("ORSupplierNightlyRoomPrice >", value, "orsuppliernightlyroomprice");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceGreaterThanOrEqualTo(String value) {
            addCriterion("ORSupplierNightlyRoomPrice >=", value, "orsuppliernightlyroomprice");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceLessThan(String value) {
            addCriterion("ORSupplierNightlyRoomPrice <", value, "orsuppliernightlyroomprice");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceLessThanOrEqualTo(String value) {
            addCriterion("ORSupplierNightlyRoomPrice <=", value, "orsuppliernightlyroomprice");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceLike(String value) {
            addCriterion("ORSupplierNightlyRoomPrice like", value, "orsuppliernightlyroomprice");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceNotLike(String value) {
            addCriterion("ORSupplierNightlyRoomPrice not like", value, "orsuppliernightlyroomprice");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceIn(List<String> values) {
            addCriterion("ORSupplierNightlyRoomPrice in", values, "orsuppliernightlyroomprice");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceNotIn(List<String> values) {
            addCriterion("ORSupplierNightlyRoomPrice not in", values, "orsuppliernightlyroomprice");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceBetween(String value1, String value2) {
            addCriterion("ORSupplierNightlyRoomPrice between", value1, value2, "orsuppliernightlyroomprice");
            return (Criteria) this;
        }

        public Criteria andOrsuppliernightlyroompriceNotBetween(String value1, String value2) {
            addCriterion("ORSupplierNightlyRoomPrice not between", value1, value2, "orsuppliernightlyroomprice");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoIsNull() {
            addCriterion("ORHotelConfirmationNo is null");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoIsNotNull() {
            addCriterion("ORHotelConfirmationNo is not null");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoEqualTo(String value) {
            addCriterion("ORHotelConfirmationNo =", value, "orhotelconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoNotEqualTo(String value) {
            addCriterion("ORHotelConfirmationNo <>", value, "orhotelconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoGreaterThan(String value) {
            addCriterion("ORHotelConfirmationNo >", value, "orhotelconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoGreaterThanOrEqualTo(String value) {
            addCriterion("ORHotelConfirmationNo >=", value, "orhotelconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoLessThan(String value) {
            addCriterion("ORHotelConfirmationNo <", value, "orhotelconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoLessThanOrEqualTo(String value) {
            addCriterion("ORHotelConfirmationNo <=", value, "orhotelconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoLike(String value) {
            addCriterion("ORHotelConfirmationNo like", value, "orhotelconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoNotLike(String value) {
            addCriterion("ORHotelConfirmationNo not like", value, "orhotelconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoIn(List<String> values) {
            addCriterion("ORHotelConfirmationNo in", values, "orhotelconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoNotIn(List<String> values) {
            addCriterion("ORHotelConfirmationNo not in", values, "orhotelconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoBetween(String value1, String value2) {
            addCriterion("ORHotelConfirmationNo between", value1, value2, "orhotelconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrhotelconfirmationnoNotBetween(String value1, String value2) {
            addCriterion("ORHotelConfirmationNo not between", value1, value2, "orhotelconfirmationno");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsIsNull() {
            addCriterion("ORBedTypeTips is null");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsIsNotNull() {
            addCriterion("ORBedTypeTips is not null");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsEqualTo(String value) {
            addCriterion("ORBedTypeTips =", value, "orbedtypetips");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsNotEqualTo(String value) {
            addCriterion("ORBedTypeTips <>", value, "orbedtypetips");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsGreaterThan(String value) {
            addCriterion("ORBedTypeTips >", value, "orbedtypetips");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsGreaterThanOrEqualTo(String value) {
            addCriterion("ORBedTypeTips >=", value, "orbedtypetips");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsLessThan(String value) {
            addCriterion("ORBedTypeTips <", value, "orbedtypetips");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsLessThanOrEqualTo(String value) {
            addCriterion("ORBedTypeTips <=", value, "orbedtypetips");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsLike(String value) {
            addCriterion("ORBedTypeTips like", value, "orbedtypetips");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsNotLike(String value) {
            addCriterion("ORBedTypeTips not like", value, "orbedtypetips");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsIn(List<String> values) {
            addCriterion("ORBedTypeTips in", values, "orbedtypetips");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsNotIn(List<String> values) {
            addCriterion("ORBedTypeTips not in", values, "orbedtypetips");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsBetween(String value1, String value2) {
            addCriterion("ORBedTypeTips between", value1, value2, "orbedtypetips");
            return (Criteria) this;
        }

        public Criteria andOrbedtypetipsNotBetween(String value1, String value2) {
            addCriterion("ORBedTypeTips not between", value1, value2, "orbedtypetips");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescIsNull() {
            addCriterion("ORRoomNameDesc is null");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescIsNotNull() {
            addCriterion("ORRoomNameDesc is not null");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescEqualTo(String value) {
            addCriterion("ORRoomNameDesc =", value, "orroomnamedesc");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescNotEqualTo(String value) {
            addCriterion("ORRoomNameDesc <>", value, "orroomnamedesc");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescGreaterThan(String value) {
            addCriterion("ORRoomNameDesc >", value, "orroomnamedesc");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescGreaterThanOrEqualTo(String value) {
            addCriterion("ORRoomNameDesc >=", value, "orroomnamedesc");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescLessThan(String value) {
            addCriterion("ORRoomNameDesc <", value, "orroomnamedesc");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescLessThanOrEqualTo(String value) {
            addCriterion("ORRoomNameDesc <=", value, "orroomnamedesc");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescLike(String value) {
            addCriterion("ORRoomNameDesc like", value, "orroomnamedesc");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescNotLike(String value) {
            addCriterion("ORRoomNameDesc not like", value, "orroomnamedesc");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescIn(List<String> values) {
            addCriterion("ORRoomNameDesc in", values, "orroomnamedesc");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescNotIn(List<String> values) {
            addCriterion("ORRoomNameDesc not in", values, "orroomnamedesc");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescBetween(String value1, String value2) {
            addCriterion("ORRoomNameDesc between", value1, value2, "orroomnamedesc");
            return (Criteria) this;
        }

        public Criteria andOrroomnamedescNotBetween(String value1, String value2) {
            addCriterion("ORRoomNameDesc not between", value1, value2, "orroomnamedesc");
            return (Criteria) this;
        }

        public Criteria andOrmaxpersonnumIsNull() {
            addCriterion("ORMaxPersonNum is null");
            return (Criteria) this;
        }

        public Criteria andOrmaxpersonnumIsNotNull() {
            addCriterion("ORMaxPersonNum is not null");
            return (Criteria) this;
        }

        public Criteria andOrmaxpersonnumEqualTo(Integer value) {
            addCriterion("ORMaxPersonNum =", value, "ormaxpersonnum");
            return (Criteria) this;
        }

        public Criteria andOrmaxpersonnumNotEqualTo(Integer value) {
            addCriterion("ORMaxPersonNum <>", value, "ormaxpersonnum");
            return (Criteria) this;
        }

        public Criteria andOrmaxpersonnumGreaterThan(Integer value) {
            addCriterion("ORMaxPersonNum >", value, "ormaxpersonnum");
            return (Criteria) this;
        }

        public Criteria andOrmaxpersonnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORMaxPersonNum >=", value, "ormaxpersonnum");
            return (Criteria) this;
        }

        public Criteria andOrmaxpersonnumLessThan(Integer value) {
            addCriterion("ORMaxPersonNum <", value, "ormaxpersonnum");
            return (Criteria) this;
        }

        public Criteria andOrmaxpersonnumLessThanOrEqualTo(Integer value) {
            addCriterion("ORMaxPersonNum <=", value, "ormaxpersonnum");
            return (Criteria) this;
        }

        public Criteria andOrmaxpersonnumIn(List<Integer> values) {
            addCriterion("ORMaxPersonNum in", values, "ormaxpersonnum");
            return (Criteria) this;
        }

        public Criteria andOrmaxpersonnumNotIn(List<Integer> values) {
            addCriterion("ORMaxPersonNum not in", values, "ormaxpersonnum");
            return (Criteria) this;
        }

        public Criteria andOrmaxpersonnumBetween(Integer value1, Integer value2) {
            addCriterion("ORMaxPersonNum between", value1, value2, "ormaxpersonnum");
            return (Criteria) this;
        }

        public Criteria andOrmaxpersonnumNotBetween(Integer value1, Integer value2) {
            addCriterion("ORMaxPersonNum not between", value1, value2, "ormaxpersonnum");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameIsNull() {
            addCriterion("ORRoomTypeName is null");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameIsNotNull() {
            addCriterion("ORRoomTypeName is not null");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameEqualTo(String value) {
            addCriterion("ORRoomTypeName =", value, "orroomtypename");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameNotEqualTo(String value) {
            addCriterion("ORRoomTypeName <>", value, "orroomtypename");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameGreaterThan(String value) {
            addCriterion("ORRoomTypeName >", value, "orroomtypename");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameGreaterThanOrEqualTo(String value) {
            addCriterion("ORRoomTypeName >=", value, "orroomtypename");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameLessThan(String value) {
            addCriterion("ORRoomTypeName <", value, "orroomtypename");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameLessThanOrEqualTo(String value) {
            addCriterion("ORRoomTypeName <=", value, "orroomtypename");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameLike(String value) {
            addCriterion("ORRoomTypeName like", value, "orroomtypename");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameNotLike(String value) {
            addCriterion("ORRoomTypeName not like", value, "orroomtypename");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameIn(List<String> values) {
            addCriterion("ORRoomTypeName in", values, "orroomtypename");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameNotIn(List<String> values) {
            addCriterion("ORRoomTypeName not in", values, "orroomtypename");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameBetween(String value1, String value2) {
            addCriterion("ORRoomTypeName between", value1, value2, "orroomtypename");
            return (Criteria) this;
        }

        public Criteria andOrroomtypenameNotBetween(String value1, String value2) {
            addCriterion("ORRoomTypeName not between", value1, value2, "orroomtypename");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderRoom
     *
     * @mbggenerated do_not_delete_during_merge Thu Feb 21 12:21:14 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderRoom
     *
     * @mbggenerated Thu Feb 21 12:21:14 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}