package com.adam.entity;

import java.util.ArrayList;
import java.util.List;

public class OrderExtendInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    public OrderExtendInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOeorderidIsNull() {
            addCriterion("OEOrderId is null");
            return (Criteria) this;
        }

        public Criteria andOeorderidIsNotNull() {
            addCriterion("OEOrderId is not null");
            return (Criteria) this;
        }

        public Criteria andOeorderidEqualTo(Long value) {
            addCriterion("OEOrderId =", value, "oeorderid");
            return (Criteria) this;
        }

        public Criteria andOeorderidNotEqualTo(Long value) {
            addCriterion("OEOrderId <>", value, "oeorderid");
            return (Criteria) this;
        }

        public Criteria andOeorderidGreaterThan(Long value) {
            addCriterion("OEOrderId >", value, "oeorderid");
            return (Criteria) this;
        }

        public Criteria andOeorderidGreaterThanOrEqualTo(Long value) {
            addCriterion("OEOrderId >=", value, "oeorderid");
            return (Criteria) this;
        }

        public Criteria andOeorderidLessThan(Long value) {
            addCriterion("OEOrderId <", value, "oeorderid");
            return (Criteria) this;
        }

        public Criteria andOeorderidLessThanOrEqualTo(Long value) {
            addCriterion("OEOrderId <=", value, "oeorderid");
            return (Criteria) this;
        }

        public Criteria andOeorderidIn(List<Long> values) {
            addCriterion("OEOrderId in", values, "oeorderid");
            return (Criteria) this;
        }

        public Criteria andOeorderidNotIn(List<Long> values) {
            addCriterion("OEOrderId not in", values, "oeorderid");
            return (Criteria) this;
        }

        public Criteria andOeorderidBetween(Long value1, Long value2) {
            addCriterion("OEOrderId between", value1, value2, "oeorderid");
            return (Criteria) this;
        }

        public Criteria andOeorderidNotBetween(Long value1, Long value2) {
            addCriterion("OEOrderId not between", value1, value2, "oeorderid");
            return (Criteria) this;
        }

        public Criteria andOeordernoIsNull() {
            addCriterion("OEOrderNo is null");
            return (Criteria) this;
        }

        public Criteria andOeordernoIsNotNull() {
            addCriterion("OEOrderNo is not null");
            return (Criteria) this;
        }

        public Criteria andOeordernoEqualTo(String value) {
            addCriterion("OEOrderNo =", value, "oeorderno");
            return (Criteria) this;
        }

        public Criteria andOeordernoNotEqualTo(String value) {
            addCriterion("OEOrderNo <>", value, "oeorderno");
            return (Criteria) this;
        }

        public Criteria andOeordernoGreaterThan(String value) {
            addCriterion("OEOrderNo >", value, "oeorderno");
            return (Criteria) this;
        }

        public Criteria andOeordernoGreaterThanOrEqualTo(String value) {
            addCriterion("OEOrderNo >=", value, "oeorderno");
            return (Criteria) this;
        }

        public Criteria andOeordernoLessThan(String value) {
            addCriterion("OEOrderNo <", value, "oeorderno");
            return (Criteria) this;
        }

        public Criteria andOeordernoLessThanOrEqualTo(String value) {
            addCriterion("OEOrderNo <=", value, "oeorderno");
            return (Criteria) this;
        }

        public Criteria andOeordernoLike(String value) {
            addCriterion("OEOrderNo like", value, "oeorderno");
            return (Criteria) this;
        }

        public Criteria andOeordernoNotLike(String value) {
            addCriterion("OEOrderNo not like", value, "oeorderno");
            return (Criteria) this;
        }

        public Criteria andOeordernoIn(List<String> values) {
            addCriterion("OEOrderNo in", values, "oeorderno");
            return (Criteria) this;
        }

        public Criteria andOeordernoNotIn(List<String> values) {
            addCriterion("OEOrderNo not in", values, "oeorderno");
            return (Criteria) this;
        }

        public Criteria andOeordernoBetween(String value1, String value2) {
            addCriterion("OEOrderNo between", value1, value2, "oeorderno");
            return (Criteria) this;
        }

        public Criteria andOeordernoNotBetween(String value1, String value2) {
            addCriterion("OEOrderNo not between", value1, value2, "oeorderno");
            return (Criteria) this;
        }

        public Criteria andOeattachmentIsNull() {
            addCriterion("OEAttachment is null");
            return (Criteria) this;
        }

        public Criteria andOeattachmentIsNotNull() {
            addCriterion("OEAttachment is not null");
            return (Criteria) this;
        }

        public Criteria andOeattachmentEqualTo(String value) {
            addCriterion("OEAttachment =", value, "oeattachment");
            return (Criteria) this;
        }

        public Criteria andOeattachmentNotEqualTo(String value) {
            addCriterion("OEAttachment <>", value, "oeattachment");
            return (Criteria) this;
        }

        public Criteria andOeattachmentGreaterThan(String value) {
            addCriterion("OEAttachment >", value, "oeattachment");
            return (Criteria) this;
        }

        public Criteria andOeattachmentGreaterThanOrEqualTo(String value) {
            addCriterion("OEAttachment >=", value, "oeattachment");
            return (Criteria) this;
        }

        public Criteria andOeattachmentLessThan(String value) {
            addCriterion("OEAttachment <", value, "oeattachment");
            return (Criteria) this;
        }

        public Criteria andOeattachmentLessThanOrEqualTo(String value) {
            addCriterion("OEAttachment <=", value, "oeattachment");
            return (Criteria) this;
        }

        public Criteria andOeattachmentLike(String value) {
            addCriterion("OEAttachment like", value, "oeattachment");
            return (Criteria) this;
        }

        public Criteria andOeattachmentNotLike(String value) {
            addCriterion("OEAttachment not like", value, "oeattachment");
            return (Criteria) this;
        }

        public Criteria andOeattachmentIn(List<String> values) {
            addCriterion("OEAttachment in", values, "oeattachment");
            return (Criteria) this;
        }

        public Criteria andOeattachmentNotIn(List<String> values) {
            addCriterion("OEAttachment not in", values, "oeattachment");
            return (Criteria) this;
        }

        public Criteria andOeattachmentBetween(String value1, String value2) {
            addCriterion("OEAttachment between", value1, value2, "oeattachment");
            return (Criteria) this;
        }

        public Criteria andOeattachmentNotBetween(String value1, String value2) {
            addCriterion("OEAttachment not between", value1, value2, "oeattachment");
            return (Criteria) this;
        }

        public Criteria andOemerchantidIsNull() {
            addCriterion("OEMerchantId is null");
            return (Criteria) this;
        }

        public Criteria andOemerchantidIsNotNull() {
            addCriterion("OEMerchantId is not null");
            return (Criteria) this;
        }

        public Criteria andOemerchantidEqualTo(Integer value) {
            addCriterion("OEMerchantId =", value, "oemerchantid");
            return (Criteria) this;
        }

        public Criteria andOemerchantidNotEqualTo(Integer value) {
            addCriterion("OEMerchantId <>", value, "oemerchantid");
            return (Criteria) this;
        }

        public Criteria andOemerchantidGreaterThan(Integer value) {
            addCriterion("OEMerchantId >", value, "oemerchantid");
            return (Criteria) this;
        }

        public Criteria andOemerchantidGreaterThanOrEqualTo(Integer value) {
            addCriterion("OEMerchantId >=", value, "oemerchantid");
            return (Criteria) this;
        }

        public Criteria andOemerchantidLessThan(Integer value) {
            addCriterion("OEMerchantId <", value, "oemerchantid");
            return (Criteria) this;
        }

        public Criteria andOemerchantidLessThanOrEqualTo(Integer value) {
            addCriterion("OEMerchantId <=", value, "oemerchantid");
            return (Criteria) this;
        }

        public Criteria andOemerchantidIn(List<Integer> values) {
            addCriterion("OEMerchantId in", values, "oemerchantid");
            return (Criteria) this;
        }

        public Criteria andOemerchantidNotIn(List<Integer> values) {
            addCriterion("OEMerchantId not in", values, "oemerchantid");
            return (Criteria) this;
        }

        public Criteria andOemerchantidBetween(Integer value1, Integer value2) {
            addCriterion("OEMerchantId between", value1, value2, "oemerchantid");
            return (Criteria) this;
        }

        public Criteria andOemerchantidNotBetween(Integer value1, Integer value2) {
            addCriterion("OEMerchantId not between", value1, value2, "oemerchantid");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidIsNull() {
            addCriterion("OEWeChatUnionId is null");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidIsNotNull() {
            addCriterion("OEWeChatUnionId is not null");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidEqualTo(String value) {
            addCriterion("OEWeChatUnionId =", value, "oewechatunionid");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidNotEqualTo(String value) {
            addCriterion("OEWeChatUnionId <>", value, "oewechatunionid");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidGreaterThan(String value) {
            addCriterion("OEWeChatUnionId >", value, "oewechatunionid");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidGreaterThanOrEqualTo(String value) {
            addCriterion("OEWeChatUnionId >=", value, "oewechatunionid");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidLessThan(String value) {
            addCriterion("OEWeChatUnionId <", value, "oewechatunionid");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidLessThanOrEqualTo(String value) {
            addCriterion("OEWeChatUnionId <=", value, "oewechatunionid");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidLike(String value) {
            addCriterion("OEWeChatUnionId like", value, "oewechatunionid");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidNotLike(String value) {
            addCriterion("OEWeChatUnionId not like", value, "oewechatunionid");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidIn(List<String> values) {
            addCriterion("OEWeChatUnionId in", values, "oewechatunionid");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidNotIn(List<String> values) {
            addCriterion("OEWeChatUnionId not in", values, "oewechatunionid");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidBetween(String value1, String value2) {
            addCriterion("OEWeChatUnionId between", value1, value2, "oewechatunionid");
            return (Criteria) this;
        }

        public Criteria andOewechatunionidNotBetween(String value1, String value2) {
            addCriterion("OEWeChatUnionId not between", value1, value2, "oewechatunionid");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameIsNull() {
            addCriterion("OEMerchantName is null");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameIsNotNull() {
            addCriterion("OEMerchantName is not null");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameEqualTo(String value) {
            addCriterion("OEMerchantName =", value, "oemerchantname");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameNotEqualTo(String value) {
            addCriterion("OEMerchantName <>", value, "oemerchantname");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameGreaterThan(String value) {
            addCriterion("OEMerchantName >", value, "oemerchantname");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameGreaterThanOrEqualTo(String value) {
            addCriterion("OEMerchantName >=", value, "oemerchantname");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameLessThan(String value) {
            addCriterion("OEMerchantName <", value, "oemerchantname");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameLessThanOrEqualTo(String value) {
            addCriterion("OEMerchantName <=", value, "oemerchantname");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameLike(String value) {
            addCriterion("OEMerchantName like", value, "oemerchantname");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameNotLike(String value) {
            addCriterion("OEMerchantName not like", value, "oemerchantname");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameIn(List<String> values) {
            addCriterion("OEMerchantName in", values, "oemerchantname");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameNotIn(List<String> values) {
            addCriterion("OEMerchantName not in", values, "oemerchantname");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameBetween(String value1, String value2) {
            addCriterion("OEMerchantName between", value1, value2, "oemerchantname");
            return (Criteria) this;
        }

        public Criteria andOemerchantnameNotBetween(String value1, String value2) {
            addCriterion("OEMerchantName not between", value1, value2, "oemerchantname");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceIsNull() {
            addCriterion("OEHotelPreference is null");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceIsNotNull() {
            addCriterion("OEHotelPreference is not null");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceEqualTo(String value) {
            addCriterion("OEHotelPreference =", value, "oehotelpreference");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceNotEqualTo(String value) {
            addCriterion("OEHotelPreference <>", value, "oehotelpreference");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceGreaterThan(String value) {
            addCriterion("OEHotelPreference >", value, "oehotelpreference");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceGreaterThanOrEqualTo(String value) {
            addCriterion("OEHotelPreference >=", value, "oehotelpreference");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceLessThan(String value) {
            addCriterion("OEHotelPreference <", value, "oehotelpreference");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceLessThanOrEqualTo(String value) {
            addCriterion("OEHotelPreference <=", value, "oehotelpreference");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceLike(String value) {
            addCriterion("OEHotelPreference like", value, "oehotelpreference");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceNotLike(String value) {
            addCriterion("OEHotelPreference not like", value, "oehotelpreference");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceIn(List<String> values) {
            addCriterion("OEHotelPreference in", values, "oehotelpreference");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceNotIn(List<String> values) {
            addCriterion("OEHotelPreference not in", values, "oehotelpreference");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceBetween(String value1, String value2) {
            addCriterion("OEHotelPreference between", value1, value2, "oehotelpreference");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceNotBetween(String value1, String value2) {
            addCriterion("OEHotelPreference not between", value1, value2, "oehotelpreference");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenIsNull() {
            addCriterion("OEHotelPreferenceEN is null");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenIsNotNull() {
            addCriterion("OEHotelPreferenceEN is not null");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenEqualTo(String value) {
            addCriterion("OEHotelPreferenceEN =", value, "oehotelpreferenceen");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenNotEqualTo(String value) {
            addCriterion("OEHotelPreferenceEN <>", value, "oehotelpreferenceen");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenGreaterThan(String value) {
            addCriterion("OEHotelPreferenceEN >", value, "oehotelpreferenceen");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenGreaterThanOrEqualTo(String value) {
            addCriterion("OEHotelPreferenceEN >=", value, "oehotelpreferenceen");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenLessThan(String value) {
            addCriterion("OEHotelPreferenceEN <", value, "oehotelpreferenceen");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenLessThanOrEqualTo(String value) {
            addCriterion("OEHotelPreferenceEN <=", value, "oehotelpreferenceen");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenLike(String value) {
            addCriterion("OEHotelPreferenceEN like", value, "oehotelpreferenceen");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenNotLike(String value) {
            addCriterion("OEHotelPreferenceEN not like", value, "oehotelpreferenceen");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenIn(List<String> values) {
            addCriterion("OEHotelPreferenceEN in", values, "oehotelpreferenceen");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenNotIn(List<String> values) {
            addCriterion("OEHotelPreferenceEN not in", values, "oehotelpreferenceen");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenBetween(String value1, String value2) {
            addCriterion("OEHotelPreferenceEN between", value1, value2, "oehotelpreferenceen");
            return (Criteria) this;
        }

        public Criteria andOehotelpreferenceenNotBetween(String value1, String value2) {
            addCriterion("OEHotelPreferenceEN not between", value1, value2, "oehotelpreferenceen");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescIsNull() {
            addCriterion("OEExpenseMoneyDesc is null");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescIsNotNull() {
            addCriterion("OEExpenseMoneyDesc is not null");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescEqualTo(String value) {
            addCriterion("OEExpenseMoneyDesc =", value, "oeexpensemoneydesc");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescNotEqualTo(String value) {
            addCriterion("OEExpenseMoneyDesc <>", value, "oeexpensemoneydesc");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescGreaterThan(String value) {
            addCriterion("OEExpenseMoneyDesc >", value, "oeexpensemoneydesc");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescGreaterThanOrEqualTo(String value) {
            addCriterion("OEExpenseMoneyDesc >=", value, "oeexpensemoneydesc");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescLessThan(String value) {
            addCriterion("OEExpenseMoneyDesc <", value, "oeexpensemoneydesc");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescLessThanOrEqualTo(String value) {
            addCriterion("OEExpenseMoneyDesc <=", value, "oeexpensemoneydesc");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescLike(String value) {
            addCriterion("OEExpenseMoneyDesc like", value, "oeexpensemoneydesc");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescNotLike(String value) {
            addCriterion("OEExpenseMoneyDesc not like", value, "oeexpensemoneydesc");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescIn(List<String> values) {
            addCriterion("OEExpenseMoneyDesc in", values, "oeexpensemoneydesc");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescNotIn(List<String> values) {
            addCriterion("OEExpenseMoneyDesc not in", values, "oeexpensemoneydesc");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescBetween(String value1, String value2) {
            addCriterion("OEExpenseMoneyDesc between", value1, value2, "oeexpensemoneydesc");
            return (Criteria) this;
        }

        public Criteria andOeexpensemoneydescNotBetween(String value1, String value2) {
            addCriterion("OEExpenseMoneyDesc not between", value1, value2, "oeexpensemoneydesc");
            return (Criteria) this;
        }

        public Criteria andOewindowdescIsNull() {
            addCriterion("OEWindowDesc is null");
            return (Criteria) this;
        }

        public Criteria andOewindowdescIsNotNull() {
            addCriterion("OEWindowDesc is not null");
            return (Criteria) this;
        }

        public Criteria andOewindowdescEqualTo(String value) {
            addCriterion("OEWindowDesc =", value, "oewindowdesc");
            return (Criteria) this;
        }

        public Criteria andOewindowdescNotEqualTo(String value) {
            addCriterion("OEWindowDesc <>", value, "oewindowdesc");
            return (Criteria) this;
        }

        public Criteria andOewindowdescGreaterThan(String value) {
            addCriterion("OEWindowDesc >", value, "oewindowdesc");
            return (Criteria) this;
        }

        public Criteria andOewindowdescGreaterThanOrEqualTo(String value) {
            addCriterion("OEWindowDesc >=", value, "oewindowdesc");
            return (Criteria) this;
        }

        public Criteria andOewindowdescLessThan(String value) {
            addCriterion("OEWindowDesc <", value, "oewindowdesc");
            return (Criteria) this;
        }

        public Criteria andOewindowdescLessThanOrEqualTo(String value) {
            addCriterion("OEWindowDesc <=", value, "oewindowdesc");
            return (Criteria) this;
        }

        public Criteria andOewindowdescLike(String value) {
            addCriterion("OEWindowDesc like", value, "oewindowdesc");
            return (Criteria) this;
        }

        public Criteria andOewindowdescNotLike(String value) {
            addCriterion("OEWindowDesc not like", value, "oewindowdesc");
            return (Criteria) this;
        }

        public Criteria andOewindowdescIn(List<String> values) {
            addCriterion("OEWindowDesc in", values, "oewindowdesc");
            return (Criteria) this;
        }

        public Criteria andOewindowdescNotIn(List<String> values) {
            addCriterion("OEWindowDesc not in", values, "oewindowdesc");
            return (Criteria) this;
        }

        public Criteria andOewindowdescBetween(String value1, String value2) {
            addCriterion("OEWindowDesc between", value1, value2, "oewindowdesc");
            return (Criteria) this;
        }

        public Criteria andOewindowdescNotBetween(String value1, String value2) {
            addCriterion("OEWindowDesc not between", value1, value2, "oewindowdesc");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeIsNull() {
            addCriterion("OEMRoomType is null");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeIsNotNull() {
            addCriterion("OEMRoomType is not null");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeEqualTo(String value) {
            addCriterion("OEMRoomType =", value, "oemroomtype");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeNotEqualTo(String value) {
            addCriterion("OEMRoomType <>", value, "oemroomtype");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeGreaterThan(String value) {
            addCriterion("OEMRoomType >", value, "oemroomtype");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeGreaterThanOrEqualTo(String value) {
            addCriterion("OEMRoomType >=", value, "oemroomtype");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeLessThan(String value) {
            addCriterion("OEMRoomType <", value, "oemroomtype");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeLessThanOrEqualTo(String value) {
            addCriterion("OEMRoomType <=", value, "oemroomtype");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeLike(String value) {
            addCriterion("OEMRoomType like", value, "oemroomtype");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeNotLike(String value) {
            addCriterion("OEMRoomType not like", value, "oemroomtype");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeIn(List<String> values) {
            addCriterion("OEMRoomType in", values, "oemroomtype");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeNotIn(List<String> values) {
            addCriterion("OEMRoomType not in", values, "oemroomtype");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeBetween(String value1, String value2) {
            addCriterion("OEMRoomType between", value1, value2, "oemroomtype");
            return (Criteria) this;
        }

        public Criteria andOemroomtypeNotBetween(String value1, String value2) {
            addCriterion("OEMRoomType not between", value1, value2, "oemroomtype");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidIsNull() {
            addCriterion("OEDetailSearchId is null");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidIsNotNull() {
            addCriterion("OEDetailSearchId is not null");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidEqualTo(String value) {
            addCriterion("OEDetailSearchId =", value, "oedetailsearchid");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidNotEqualTo(String value) {
            addCriterion("OEDetailSearchId <>", value, "oedetailsearchid");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidGreaterThan(String value) {
            addCriterion("OEDetailSearchId >", value, "oedetailsearchid");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidGreaterThanOrEqualTo(String value) {
            addCriterion("OEDetailSearchId >=", value, "oedetailsearchid");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidLessThan(String value) {
            addCriterion("OEDetailSearchId <", value, "oedetailsearchid");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidLessThanOrEqualTo(String value) {
            addCriterion("OEDetailSearchId <=", value, "oedetailsearchid");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidLike(String value) {
            addCriterion("OEDetailSearchId like", value, "oedetailsearchid");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidNotLike(String value) {
            addCriterion("OEDetailSearchId not like", value, "oedetailsearchid");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidIn(List<String> values) {
            addCriterion("OEDetailSearchId in", values, "oedetailsearchid");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidNotIn(List<String> values) {
            addCriterion("OEDetailSearchId not in", values, "oedetailsearchid");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidBetween(String value1, String value2) {
            addCriterion("OEDetailSearchId between", value1, value2, "oedetailsearchid");
            return (Criteria) this;
        }

        public Criteria andOedetailsearchidNotBetween(String value1, String value2) {
            addCriterion("OEDetailSearchId not between", value1, value2, "oedetailsearchid");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameIsNull() {
            addCriterion("OEElongPName is null");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameIsNotNull() {
            addCriterion("OEElongPName is not null");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameEqualTo(String value) {
            addCriterion("OEElongPName =", value, "oeelongpname");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameNotEqualTo(String value) {
            addCriterion("OEElongPName <>", value, "oeelongpname");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameGreaterThan(String value) {
            addCriterion("OEElongPName >", value, "oeelongpname");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameGreaterThanOrEqualTo(String value) {
            addCriterion("OEElongPName >=", value, "oeelongpname");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameLessThan(String value) {
            addCriterion("OEElongPName <", value, "oeelongpname");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameLessThanOrEqualTo(String value) {
            addCriterion("OEElongPName <=", value, "oeelongpname");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameLike(String value) {
            addCriterion("OEElongPName like", value, "oeelongpname");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameNotLike(String value) {
            addCriterion("OEElongPName not like", value, "oeelongpname");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameIn(List<String> values) {
            addCriterion("OEElongPName in", values, "oeelongpname");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameNotIn(List<String> values) {
            addCriterion("OEElongPName not in", values, "oeelongpname");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameBetween(String value1, String value2) {
            addCriterion("OEElongPName between", value1, value2, "oeelongpname");
            return (Criteria) this;
        }

        public Criteria andOeelongpnameNotBetween(String value1, String value2) {
            addCriterion("OEElongPName not between", value1, value2, "oeelongpname");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoIsNull() {
            addCriterion("OEOtherProductInfo is null");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoIsNotNull() {
            addCriterion("OEOtherProductInfo is not null");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoEqualTo(String value) {
            addCriterion("OEOtherProductInfo =", value, "oeotherproductinfo");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoNotEqualTo(String value) {
            addCriterion("OEOtherProductInfo <>", value, "oeotherproductinfo");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoGreaterThan(String value) {
            addCriterion("OEOtherProductInfo >", value, "oeotherproductinfo");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoGreaterThanOrEqualTo(String value) {
            addCriterion("OEOtherProductInfo >=", value, "oeotherproductinfo");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoLessThan(String value) {
            addCriterion("OEOtherProductInfo <", value, "oeotherproductinfo");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoLessThanOrEqualTo(String value) {
            addCriterion("OEOtherProductInfo <=", value, "oeotherproductinfo");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoLike(String value) {
            addCriterion("OEOtherProductInfo like", value, "oeotherproductinfo");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoNotLike(String value) {
            addCriterion("OEOtherProductInfo not like", value, "oeotherproductinfo");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoIn(List<String> values) {
            addCriterion("OEOtherProductInfo in", values, "oeotherproductinfo");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoNotIn(List<String> values) {
            addCriterion("OEOtherProductInfo not in", values, "oeotherproductinfo");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoBetween(String value1, String value2) {
            addCriterion("OEOtherProductInfo between", value1, value2, "oeotherproductinfo");
            return (Criteria) this;
        }

        public Criteria andOeotherproductinfoNotBetween(String value1, String value2) {
            addCriterion("OEOtherProductInfo not between", value1, value2, "oeotherproductinfo");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameIsNull() {
            addCriterion("OESupplierName is null");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameIsNotNull() {
            addCriterion("OESupplierName is not null");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameEqualTo(String value) {
            addCriterion("OESupplierName =", value, "oesuppliername");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameNotEqualTo(String value) {
            addCriterion("OESupplierName <>", value, "oesuppliername");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameGreaterThan(String value) {
            addCriterion("OESupplierName >", value, "oesuppliername");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameGreaterThanOrEqualTo(String value) {
            addCriterion("OESupplierName >=", value, "oesuppliername");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameLessThan(String value) {
            addCriterion("OESupplierName <", value, "oesuppliername");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameLessThanOrEqualTo(String value) {
            addCriterion("OESupplierName <=", value, "oesuppliername");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameLike(String value) {
            addCriterion("OESupplierName like", value, "oesuppliername");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameNotLike(String value) {
            addCriterion("OESupplierName not like", value, "oesuppliername");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameIn(List<String> values) {
            addCriterion("OESupplierName in", values, "oesuppliername");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameNotIn(List<String> values) {
            addCriterion("OESupplierName not in", values, "oesuppliername");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameBetween(String value1, String value2) {
            addCriterion("OESupplierName between", value1, value2, "oesuppliername");
            return (Criteria) this;
        }

        public Criteria andOesuppliernameNotBetween(String value1, String value2) {
            addCriterion("OESupplierName not between", value1, value2, "oesuppliername");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 19 16:12:49 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table OrderExtendInfo
     *
     * @mbggenerated Tue Feb 19 16:12:49 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}