package com.example.newdemodemo.mapper;

import com.example.newdemodemo.entity.OrderDetail;
import com.example.newdemodemo.entity.OrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetail
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    int deleteByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetail
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetail
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetail
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetail
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    List<OrderDetail> selectByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetail
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    OrderDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetail
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetail
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    int updateByExample(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetail
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    int updateByPrimaryKeySelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OrderDetail
     *
     * @mbg.generated Mon Feb 18 13:57:58 CST 2019
     */
    int updateByPrimaryKey(OrderDetail record);
}